#!/usr/bin/env python3
"""
build_provenance_ledger.py — every pipeline output, and every exhibit that uses it.

WHY A NEW ONE

  notes/ledgers/TABLE_LEDGER.md is built from tools/figure_table_manifest.csv,
  a hand-maintained file that had drifted: it listed 48 tables of which 20 were
  flagged, 19 rows carried an EMPTY source, and it still named
  Newborough_Methods_Supplement_v1_9_6.odt while the live document was v2_0_6.
  A ledger nobody can trust is worse than none, because it answers questions
  wrongly rather than refusing to.

  It also answered the wrong question. Keyed by document, it says "table N of
  document D came from file F". The question that matters when a script's output
  changes is the INVERSE: which exhibits, in which documents, have to be
  re-checked? On 2026-09-19 that question could only be answered by grep.

WHAT IT DOES

  Derives, from live sources only:

    report tables    ODT captions in document order + tools/table_configs.py
    report figures   tools/figure_map.csv (regenerated by tools/figure_map.py)
    paper exhibits   each paper's own exhibit manifests under docs/papers/

  and writes notes/ledgers/PROVENANCE_LEDGER.md keyed BY OUTPUT FILE: each CSV
  or PNG, then every document and exhibit number that renders it. An output
  cited by nothing is listed too — that is a real state, not an omission.

  Nothing here is hand-maintained. If a document is renumbered, the ledger moves
  with it on the next run.

Usage:
    python3 tools/build_provenance_ledger.py
    python3 tools/build_provenance_ledger.py --check    # stale = non-zero exit
"""
from __future__ import annotations

__version__ = "1.0.0"  # Hollingham (2026) — 2026-09-19.

import argparse
import csv as _csv
import pathlib
import re
import sys
import zipfile
from collections import defaultdict

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
OUT = REPO / "notes/ledgers/PROVENANCE_LEDGER.md"
TAG = re.compile(r"<[^>]+>")
CAPTION = re.compile(r"\s*Tables?\s+(\d+(?:\.\d+)?)\s*([a-d])?\s*[:.]\s*(.*)", re.S)
CHAPTERS = ["report6", "report7", "report8", "report9", "report10",
            "report11", "report12"]


def _first_text_after(xml: str, pos: int, reach: int = 3000) -> str:
    for m in re.finditer(r"<text:p\b[^>]*>(.*?)</text:p>", xml[pos:pos + reach], re.S):
        txt = TAG.sub("", m.group(1)).strip()
        if txt:
            return txt
    return ""


def report_tables():
    """(document, 'Table N', caption, {sources}) for every numbered report table."""
    try:
        from table_configs import TABLES
    except Exception:
        TABLES = []
    cfg_src = {}
    for cfg in TABLES:
        if not str(cfg.get("id", "")).startswith("report"):
            continue
        m = re.search(r"Table\s+(\d+\.\d+)\s*(?:\(([a-d])\))?", cfg.get("caption", ""))
        if m:
            cfg_src.setdefault(m.group(1) + (m.group(2) or ""), set()).update(
                pathlib.Path(v).name for v in cfg.get("sources", {}).values())
    f = REPO / "tools/figure_table_sources.csv"
    if f.exists():
        with f.open(newline="", encoding="utf-8") as fh:
            for r in _csv.DictReader(fh):
                if r.get("type") == "Table" and r.get("document", "").startswith("report"):
                    cfg_src.setdefault(r["number"], set()).add(
                        pathlib.Path(r["source"]).name)
    out = []
    for stem in CHAPTERS:
        odt = REPO / "report_edits/odt" / f"{stem}.odt"
        if not odt.exists():
            continue
        xml = zipfile.ZipFile(odt).read("content.xml").decode("utf-8")
        for m in re.finditer(r'<table:table table:name="([^"]+)"', xml):
            end = xml.find("</table:table>", m.end()) + len("</table:table>")
            cap = CAPTION.match(_first_text_after(xml, end))
            if not cap:
                continue
            num = cap.group(1) + (cap.group(2) or "")
            # No rstrip fallback for a LETTERED number: "1.4c" falling back to
            # "1.4" collects every source in the 1.4a-d group, which listed the
            # specific-yield CSV against the volumetric balance table.
            src = cfg_src.get(num) or set()
            if not src and num[-1] not in "abcd":
                src = cfg_src.get(num.rstrip("abcd")) or set()
            out.append((f"{stem}.odt", f"Table {num}", cap.group(3)[:80].strip(), src))
    return out


def report_figures():
    out = []
    f = REPO / "tools/figure_map.csv"
    if not f.exists():
        return out
    with f.open(newline="", encoding="utf-8") as fh:
        for r in _csv.DictReader(fh):
            out.append((r["document"], f"Figure {r['number']}",
                        (r.get("caption") or "")[:80].strip(),
                        {pathlib.Path(r["source"]).name} if r.get("source") else set()))
    return out


def paper_exhibits():
    out = []
    for n in (1, 2):
        for kind, word in (("TABLES", "Table"), ("FIGURES", "Figure")):
            p = REPO / "docs" / "papers" / f"paper_{n}" / f"PAPER{n}_{kind}.md"
            if not p.exists():
                continue
            for line in p.read_text(encoding="utf-8").split("\n"):
                if not line.startswith("|"):
                    continue
                cells = [c.strip().strip("`") for c in line.strip().strip("|").split("|")]
                if len(cells) < 2 or not cells[0].isdigit():
                    continue
                srcs = set()
                for cell in cells[1:3]:
                    srcs.update(pathlib.Path(x).name
                                for x in re.findall(r"[\w./-]+\.(?:csv|png|jpg)", cell))
                # TABLES: | N | source | script | content |   -> content is last
                # FIGURES: | N | rendered | source | script | topic | class |
                desc = cells[-1] if kind == "TABLES" else (
                    cells[-2] if len(cells) >= 5 else cells[-1])
                out.append((f"Paper {n}", f"{word} {cells[0]}", desc[:80], srcs))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rows = report_tables() + report_figures() + paper_exhibits()
    by_src = defaultdict(list)
    for doc, num, cap, srcs in rows:
        for s in srcs or {"(no source recorded)"}:
            by_src[s].append((doc, num, cap))

    produced = {p.name for p in (REPO / "outputs").rglob("*")
                if p.suffix in (".csv", ".png", ".jpg")}
    cited = {k for k in by_src if k != "(no source recorded)"}

    L = ["<!-- GENERATED LEDGER — do not edit.",
         "     Regenerate with: python3 tools/build_provenance_ledger.py -->", "",
         "# PROVENANCE_LEDGER — every pipeline output and the exhibits that render it",
         "",
         "*Derived live from the ODT captions, `tools/table_configs.py`, "
         "`tools/figure_map.csv` and the papers' own exhibit manifests. Keyed by "
         "OUTPUT FILE, so the question it answers is: this script's output changed "
         "— which exhibits, in which documents, have to be re-checked?*", "",
         f"**{len(rows)} exhibit(s)** across the corpus, drawing on "
         f"**{len(cited)} output file(s)**.", "",
         "| Output file | Document | Exhibit | Caption |", "|---|---|---|---|"]
    for src in sorted(by_src):
        for i, (doc, num, cap) in enumerate(sorted(by_src[src])):
            L.append(f"| {'`'+src+'`' if i == 0 else ''} | {doc} | {num} | {cap} |")

    orphan = sorted(n for n in produced - cited
                    if n.endswith((".csv", ".png")) and not n.startswith("."))
    L += ["", f"## Outputs no exhibit renders ({len(orphan)})", "",
          "*Not a fault on its own — most outputs are intermediates. Listed so "
          "that an output which SHOULD be on a page is visible when it is not.*",
          ""]
    L += ["- `" + n + "`" for n in orphan[:400]]
    text = "\n".join(L) + "\n"

    if args.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print("build_provenance_ledger: STALE — regenerate")
            return 1
        print("build_provenance_ledger: OK — ledger matches the documents")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}  ({len(rows)} exhibit(s), "
          f"{len(cited)} output(s) cited, {len(orphan)} uncited)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
