#!/usr/bin/env python3
"""Does a committed vp2 frame show the imagery its label claims?

WHY. Two captures in the 2026-09-12 tiled series carry a status bar that is
wrong about their own imagery: `…17-05-08.png` reads 5/27/2010 and is the same
ground as a frame whose bar reads 12/31/2009, and `…17-05-56.png` reads 3/24/2017
and is the same ground as one reading 12/31/2016 (measured at 0.44 % and 0.47 %
of the window, in icon blobs only). So the bar is the TIMELINE POSITION and not
always the capture. Two of the labels this implicates are load-bearing:
2010-05-27 is the flood read's negative control and 2017-03-24 is the frame
`FLOOD_OTSU_MAX_Z` = −0.75 excludes.

**Resolution is not authority over date, and this tool does not assume it is.**
Google Earth serves different imagery at different zoom levels for the same
timeline position, so a 2 m/px tile labelled 2009-12-31 and a 2.884 m/px frame
labelled 2010-05-27 can each be truthful about their own pixels. What the tiles
give is the first chance to COMPARE: both series are now registered, so the
ground can be put on one grid and scored.

EARLIER BEATS LATER, where two labels show the same imagery (Martin,
2026-09-12), and the reason is an asymmetry rather than a preference: imagery
cannot predate its own capture, but it can persist forward in a later timeline
slot — which is exactly what the stale March 2020 block over the eastern warren
already does. So if one surface appears at labels D1 < D2, the capture is at or
before D1, and D1 is the better estimate while D2 is only an upper bound. THE
RULE IS VOID WHERE THE TWO LABELS SHOW DIFFERENT IMAGERY: then neither bounds
the other and earlier/later says nothing. Establishing which case holds is this
tool's whole job.

WHAT IT MEASURES, AND WHAT THE NUMBER IS WORTH. Frames are sampled onto a common
OSGB grid through their own fitted transforms (Script 41's `_sample_to_grid`) and
scored by Pearson correlation over the cells both frames saw, inside the warren.
Across resolutions an exact-equality test is not available — resampling alone
moves every pixel — so the score is continuous and MEANINGLESS IN ISOLATION. It
is read only against the two calibrations this tool computes alongside it:

  SAME     pairs whose imagery is already established as one surface.
  DIFFERENT pairs of genuinely different dates over the same ground.

A verdict is the ranking plus the separation between those two bands. Where the
bands overlap, the answer is "this cannot tell", and that is a result.

Usage:
    python3 tools/crossres_date_check.py --register   # stage 1, cache transforms
    python3 tools/crossres_date_check.py --score      # stage 2, the matrix
    python3 tools/crossres_date_check.py --res 4.0 --score
"""
from __future__ import annotations

__version__ = "1.0.0"  # Hollingham (2026) - 2026-09-12. New: the
#   cross-resolution date check, for D-159. Built after two status bars in
#   the tiled series were found to disagree with their own imagery.

import argparse
import importlib.util as iu
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from utils.console_utils import banner, info, phase, saved, step, warn  # noqa: E402

OUT = REPO / "working" / "updates"
CACHE = OUT / "crossres_transforms.json"
SCORES = OUT / "crossres_scores.csv"
TILES = REPO / "data" / "geo" / "slacks"
INVENTORY = OUT / "W159_registration_inventory.csv"
MANIFEST = REPO / "data" / "geo" / "aerial_manifest.csv"
DEFAULT_RES_M = 4.0          # coarser than both series; vp2 is 2.884 m/px
MIN_CELLS = 2000             # below this an overlap is too small to read


def _m41():
    spec = iu.spec_from_file_location("m41", str(REPO / "src" / "41_canopy_cover.py"))
    m = iu.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _ic():
    spec = iu.spec_from_file_location("ic", str(REPO / "tools" / "ingest_capture.py"))
    m = iu.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _tabulate(fitted, E, N) -> list:
    """A fitted transform, stored as the (E, N) -> (u, v) pairs it produces.

    The transform is a closure and cannot be serialised; a homography refitted to
    points GENERATED by a homography is that same homography, so tabulating it on
    the control net and refitting with `_homography` reproduces it exactly. That
    also makes the cache auditable: it holds coordinates, not pickled code.
    """
    u, v = fitted(np.asarray(E, float), np.asarray(N, float))
    return [[float(a), float(b), float(c), float(d)]
            for a, b, c, d in zip(E, N, np.asarray(u), np.asarray(v))]


def _fit_vp2(m41, path, E, N):
    """Register one vp2 frame on the DIPWELL placemarks, by their blue tips.

    NOT `ingest_capture._locate`: that finds white RINGS, which is what
    `georef_grid.kml` renders as, and the committed series carries the blue
    pushpin placemarks instead. Run on a vp2 frame the ring detector returns
    55-221 "tips" and matches none of them — false positives, every one.

    NOT `_register_all` either, though that is Script 41's own routine and would
    be the first choice. It registers every frame in one pass, seeding from
    whichever carries the control outline and chaining between constellation
    groups, and over the 52 manifest frames it does not finish inside the
    bridge's per-call limit. Here a single frame is wanted, so the well seeder
    does it directly: measured on five vp2 markers frames, 86-87 of ~100
    placemarks matched at 2.82-2.88 m/px.

    Both radius schedules are tried and the lower residual kept, which is the
    selection rule `_register_all` applies across its three seeds. The residual
    this returns (7-9 m, 2.5-3 px) is ABOUT TWICE Script 41's 3.93 m and is
    reported for that reason: it is a ceiling on what a ground comparison through
    this transform can resolve, and it is the same ceiling for every pair, so it
    costs absolute agreement and not the ranking between tile dates.
    """
    from PIL import Image                                     # noqa: PLC0415
    a = np.asarray(Image.open(path).convert("RGB")).astype(int)
    tips = m41._detect_markers(a)
    if len(tips) < m41.CANOPY_MIN_CONTROL_POINTS:
        return None
    seed = m41._seed_from_wells(tips, E, N)
    if seed is None:
        return None
    best = None
    for radii in (m41.CANOPY_MATCH_RADII_NARROW, m41.CANOPY_MATCH_RADII_WIDE):
        try:
            pred, r, P, n = m41._match_and_fit(tips, E, N, seed, tuple(radii))
        except Exception:                                     # noqa: BLE001
            continue
        if n < m41.CANOPY_MIN_CONTROL_POINTS:
            continue
        if best is None or np.median(r) < np.median(best[1]):
            best = (pred, r, P, n)
    if best is None:
        return None
    pred, r, P, n = best
    u, v = pred(E, N)
    dpx = np.hypot(np.diff(u), np.diff(v))
    dm = np.hypot(np.diff(E), np.diff(N))
    ok = (dpx > 1) & (dm > 1)
    gsd = float(np.median(dm[ok] / dpx[ok])) if ok.any() else float("nan")
    return {"fitted": pred, "n_matched": int(n), "gsd_m": gsd,
            "residual_m": float(np.median(r)) * gsd,
            "n_tips": int(len(tips))}


def _register(a) -> int:
    phase(1, "registering both series, and caching each transform")
    m41, ic = _m41(), _ic()
    grid = pd.read_csv(ic.GRID_CSV, float_precision="round_trip")
    gE, gN = grid["easting"].values, grid["northing"].values
    cache = {"res_m": None, "frames": {}}
    if CACHE.exists():
        cache = json.loads(CACHE.read_text())

    # ── the committed vp2 series, through Script 41's own registration ──────
    # THE CONTROL POINTS ARE SCRIPT 41's OWN — the dipwell placemarks from
    # INT_LOCATIONS, taken from its module rather than restated here.
    from utils.paths import INT_LOCATIONS                     # noqa: PLC0415
    man = pd.read_csv(MANIFEST, float_precision="round_trip")
    w = pd.read_csv(INT_LOCATIONS, float_precision="round_trip")
    ec = next(c for c in w.columns if c.lower() in ("easting", "e", "x"))
    nc = next(c for c in w.columns if c.lower() in ("northing", "n", "y"))
    wE, wN = w[ec].values.astype(float), w[nc].values.astype(float)

    # ONLY THE MARKERS FRAMES ARE FITTED. A vp2 frame with no placemarks has no
    # control in it and cannot self-register; it takes its twin's transform, the
    # same discipline the tiled series uses, and the twin is established by
    # MEASURING the ground rather than by trusting the `m` in the filename.
    vp2 = man[man["viewpoint"].astype(str).str.startswith("vp2")]
    names = [str(f) for f in vp2["filename"]
             if (REPO / "data" / "geo" / str(f)).exists()]
    dated = {n_: str(vp2[vp2["filename"] == n_]["imagery_date"].iloc[0])[:10]
             for n_ in names}
    info(f"{len(names)} vp2 frame(s) on disk")
    fits = {}
    for n_ in names:
        if n_ in cache["frames"]:
            continue
        r = _fit_vp2(m41, REPO / "data" / "geo" / n_, wE, wN)
        if r is None:
            continue
        fits[n_] = r
        cache["frames"][n_] = {
            "series": "vp2", "date": dated.get(n_), "gsd_m": r["gsd_m"],
            "residual_m": r["residual_m"], "n_matched": r["n_matched"],
            "locate_source": None,
            "pairs": _tabulate(r["fitted"], wE, wN),
        }
        info(f"  {n_}: {r['n_matched']} of {r['n_tips']} placemark(s), "
             f"{r['gsd_m']:.3f} m/px, residual {r['residual_m']:.2f} m")
        CACHE.write_text(json.dumps(cache))
    step(f"{len(fits)} vp2 frame(s) fitted on their own placemarks")

    # the unfitted vp2 frames inherit, where the ground says they may
    done = {k for k, v in cache["frames"].items() if v["series"] == "vp2"}
    n_tw = 0
    for n_ in names:
        if n_ in done:
            continue
        best = None
        for s_ in sorted(done):
            m = ic._same_view(REPO / "data" / "geo" / n_,
                              REPO / "data" / "geo" / s_, m41)
            if m is None:
                continue
            if best is None or m["diff_frac"] < best[0]["diff_frac"]:
                best = (m, s_)
        if best is None or best[0]["diff_frac"] > ic.TWIN_MAX_DIFF_FRAC:
            warn(f"  {n_}: no vp2 frame within "
                 f"{ic.TWIN_MAX_DIFF_FRAC * 100:.0f} % of its ground; "
                 f"left unregistered"
                 + (f" (closest {best[1]} at {best[0]['diff_frac'] * 100:.1f} %)"
                    if best else ""))
            continue
        m, s_ = best
        src = cache["frames"][s_]
        cache["frames"][n_] = dict(src, date=dated.get(n_), locate_source=s_,
                                   twin_diff_pct=round(m["diff_frac"] * 100, 3))
        info(f"  {n_}: from {s_} — ground differs on "
             f"{m['diff_frac'] * 100:.2f} % in {m['n_blobs']} blob(s)"
             + ("" if dated.get(n_) == src["date"]
                else f"; NOTE the two carry DIFFERENT labels, "
                     f"{dated.get(n_)} and {src['date']}"))
        n_tw += 1
        CACHE.write_text(json.dumps(cache))
    step(f"{n_tw} vp2 frame(s) located from a twin")

    # ── the tiles, through the ingest tool ──────────────────────────────────
    inv = pd.read_csv(INVENTORY, float_precision="round_trip")
    want = inv[inv["status"] == "registered"]
    if a.dates:
        keep = set(a.dates.split(","))
        want = want[want["date"].astype(str).isin(keep)]
    info(f"{len(want)} registered tile(s) to cache"
         + (f" (dates {a.dates})" if a.dates else ""))
    nets = {"georef": (gE, gN)}
    n = 0
    for _, r in want.iterrows():
        if str(r["file"]) in cache["frames"]:
            continue
        p = TILES / str(r["file"])
        if not p.exists():
            continue
        sb = {"eye_alt_km": None}
        loc = ic._locate(p, m41, nets, sb, 5.0)
        if loc.get("fitted") is None:
            warn(f"  {p.name}: did not register this time; skipped")
            continue
        cache["frames"][p.name] = {
            "series": "tile",
            "date": str(r["date"])[:10],
            "gsd_m": float(loc["gsd_m"]),
            "residual_m": float(loc["residual_median_m"]),
            "pairs": _tabulate(loc["fitted"], gE, gN),
        }
        n += 1
        CACHE.write_text(json.dumps(cache))       # survive the bridge time limit
    step(f"{n} tile(s) added; {len(cache['frames'])} frame(s) in the cache")
    CACHE.write_text(json.dumps(cache))
    saved(CACHE.name)
    return 0


def _score(a) -> int:
    phase(2, "scoring every vp2 frame against every tile, on common ground")
    if not CACHE.exists():
        warn("no transform cache; run --register first")
        return 1
    from PIL import Image
    m41 = _m41()
    cache = json.loads(CACHE.read_text())
    frames = cache["frames"]
    vp2 = {k: v for k, v in frames.items() if v["series"] == "vp2"}
    if a.vp2:
        keep = [x.strip() for x in a.vp2.split(",") if x.strip()]
        vp2 = {k: v for k, v in vp2.items() if any(x in k for x in keep)}
    tiles = {k: v for k, v in frames.items() if v["series"] == "tile"}
    info(f"{len(vp2)} vp2 frame(s) against {len(tiles)} tile(s), "
         f"{a.res:.1f} m grid")
    if not vp2 or not tiles:
        warn("need both series in the cache")
        return 1

    from utils.warren_mask import warren_on                  # noqa: PLC0415
    site = warren_on(max(v["date"] for v in frames.values() if v["date"]))
    minx, miny, maxx, maxy = site.bounds
    res = float(a.res)
    ge = np.arange(np.floor(minx / res) * res, maxx + res, res)
    gn = np.arange(np.ceil(maxy / res) * res, miny - res, -res)
    EE, NN = np.meshgrid(ge, gn)
    inside = _inside(site, EE, NN)
    info(f"  grid {EE.shape[1]} x {EE.shape[0]}, {int(inside.sum())} cell(s) "
         f"inside the warren")

    def sampled(name):
        d = frames[name]
        p = (TILES / name) if d["series"] == "tile" else (REPO / "data" / "geo" / name)
        lum = m41._lum(np.asarray(Image.open(p).convert("RGB")).astype(int))
        H = m41._homography(np.asarray(d["pairs"], float))
        v, ok = m41._sample_to_grid(lum, H, EE, NN)
        return v, (ok & inside & np.isfinite(v))

    cacheS = {}
    rows = []
    for vn in sorted(vp2):
        va, vok = cacheS.setdefault(vn, sampled(vn))
        for tn in sorted(tiles):
            ta, tok = cacheS.setdefault(tn, sampled(tn))
            r, dx, dy, n = _best_offset(va, vok, ta, tok, a.shift)
            if n < MIN_CELLS:
                continue
            rows.append({
                "vp2_frame": vn, "vp2_date": vp2[vn]["date"],
                "tile": tn, "tile_date": tiles[tn]["date"],
                "cells": n, "r": round(r, 4),
                "offset_e_m": round(dx * float(a.res), 1),
                "offset_n_m": round(-dy * float(a.res), 1),
                "same_label": vp2[vn]["date"] == tiles[tn]["date"],
            })
    if not rows:
        warn(f"no pair overlaps by {MIN_CELLS} cell(s); nothing to score")
        return 1
    D = pd.DataFrame(rows).sort_values(["vp2_frame", "r"], ascending=[True, False])
    D.to_csv(SCORES, index=False)
    saved(SCORES.name)

    # ── the calibration the score is read against ───────────────────────────
    same = D[D["same_label"]]["r"]
    diff = D[~D["same_label"]]["r"]
    step("calibration — what this score does and does not separate:")
    for lab, s in (("pairs whose LABELS agree", same),
                   ("pairs whose labels differ", diff)):
        if len(s):
            info(f"  {lab:26s} n {len(s):4d}  r median {s.median():.3f}  "
                 f"range {s.min():.3f} to {s.max():.3f}")
    if len(same) and len(diff):
        sep = same.median() - diff.median()
        info(f"  separation of the medians: {sep:+.3f}")
        if sep < 0.05:
            warn("  THE BANDS DO NOT SEPARATE. A ranking below is not evidence "
                 "about any frame's date; correlation across these resolutions "
                 "cannot answer the question and a different test is needed.")

    step("each vp2 frame, its best-matching tile dates:")
    for vn, g in D.groupby("vp2_frame"):
        g = g.sort_values("r", ascending=False)
        own = g[g["same_label"]]
        best = g.iloc[0]
        rank = (int((g["r"] > own["r"].max()).sum()) + 1) if len(own) else None
        info(f"  {vn}  (label {vp2[vn]['date']})")
        info(f"    best tile: {best['tile_date']} r {best['r']:.3f} "
             f"({best['cells']} cells)")
        if rank is not None:
            info(f"    its OWN label ranks {rank} of "
                 f"{g['tile_date'].nunique()} tile date(s), "
                 f"best r {own['r'].max():.3f}")
        else:
            info("    no tile carries its label, so there is no own-label "
                 "control for this frame")
    info("NOTHING IS RE-DATED BY THIS TOOL. It writes a score table; changing a "
         "frame's date is a decision, and for 2010-05-27 and 2017-03-24 it is a "
         "decision about the flood read's calibration.")
    return 0


def _best_offset(va, vok, ta, tok, shift):
    """Peak correlation over a small rigid shift, and where the peak sat.

    WHY THIS IS NOT OPTIONAL. The vp2 transforms fitted here carry a residual of
    7-9 m and the tiles 1.4-2.0 m, on a grid of a few metres. Dune texture
    decorrelates over a couple of cells, so comparing the two series cell-for-cell
    measures the registration error and not the ground: run without a shift, the
    same-label pairs scored r median 0.005 against 0.011 for pairs whose labels
    differ — no separation at all, which is a statement about the transforms
    rather than about any frame's date.

    Shifting the SAMPLED GRIDS by whole cells rather than re-sampling keeps this
    cheap: it is array slicing, so the whole offset search costs about what one
    extra comparison would.

    The offset at the peak is reported because it is itself diagnostic: a
    consistent offset across every pair involving one frame is that frame's
    registration error, while a pair that only agrees at a large and lonely
    offset is not agreeing.
    """
    best = (float("-inf"), 0, 0, 0)
    for dy in range(-shift, shift + 1):
        for dx in range(-shift, shift + 1):
            A = np.roll(np.roll(va, dy, axis=0), dx, axis=1)
            Aok = np.roll(np.roll(vok, dy, axis=0), dx, axis=1)
            both = Aok & tok
            n = int(both.sum())
            if n < MIN_CELLS:
                continue
            r = _pearson(A[both], ta[both])
            if np.isfinite(r) and r > best[0]:
                best = (float(r), dx, dy, n)
    return best if np.isfinite(best[0]) else (float("nan"), 0, 0, 0)


def _inside(geom, EE, NN):
    from PIL import Image, ImageDraw                          # noqa: PLC0415
    h, w = EE.shape
    minx, maxy = EE[0, 0], NN[0, 0]
    res = float(EE[0, 1] - EE[0, 0])
    img = Image.new("1", (w, h), 0)
    dr = ImageDraw.Draw(img)
    for poly in (list(geom.geoms) if geom.geom_type == "MultiPolygon" else [geom]):
        cc = list(poly.exterior.coords)[:-1]
        dr.polygon([((c[0] - minx) / res, (maxy - c[1]) / res) for c in cc], fill=1)
    return np.array(img, dtype=bool)


def _pearson(x, y) -> float:
    """Correlation after a ROBUST per-frame rescale.

    Two captures of one surface differ in exposure and in whatever Google Earth
    did to them, so the comparison must be invariant to a shift and a scale. The
    median and IQR give that without letting a bright sand patch set the scale.
    """
    def z(v):
        q1, q3 = np.percentile(v, [25, 75])
        s = (q3 - q1) or 1.0
        return (v - np.median(v)) / s
    xz, yz = z(np.asarray(x, float)), z(np.asarray(y, float))
    if xz.std() == 0 or yz.std() == 0:
        return float("nan")
    return float(np.corrcoef(xz, yz)[0, 1])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--register", action="store_true")
    ap.add_argument("--score", action="store_true")
    ap.add_argument("--res", type=float, default=DEFAULT_RES_M)
    ap.add_argument("--vp2", default="",
                    help="comma-separated substrings; score only these vp2 frames")
    ap.add_argument("--shift", type=int, default=3,
                    help="rigid search, in grid cells either way")
    ap.add_argument("--dates", default="",
                    help="comma-separated tile dates to cache (default: all)")
    a = ap.parse_args()
    banner("Cross-resolution date check", __version__)
    if not (a.register or a.score):
        warn("give --register, --score, or both")
        return 1
    rc = 0
    if a.register:
        rc = _register(a)
    if rc == 0 and a.score:
        rc = _score(a)
    return rc


if __name__ == "__main__":
    sys.exit(main())
