#!/usr/bin/env python3
"""Write a KML of the monitoring network for journal submission (T-24 / S6).

JHRS asks for a KML or KMZ of site locations with the submission. This writes
`data/geo/well_locations.kml` from the committed pipeline outputs, so the file
is regenerable and traceable rather than hand-drawn.

WHICH WELLS. The classified network is 66 reference + 22 extended = 88 dipwells,
counted from `01_wells_reference.csv` and `01_wells_extended.csv` — never from
`01_wells_clean.csv`, which carries a different count again. `01_locations.csv`
holds 99 rows: the network, the Llyn Rhos-Ddu lake gauge, and points that are
not part of the classified network at all. So membership comes from the two
network files and coordinates come from `01_locations.csv`, keyed on Match_ID.

The lake gauge is emitted in its own folder, labelled. It is NOT a dipwell —
"89 measuring points" includes it, 88 dipwells does not — and keeping it in a
separate folder means neither count can be read off this file by accident.

COORDINATES. Well positions are OSGB36 / British National Grid (EPSG:27700);
KML requires WGS84 lon/lat (EPSG:4326). pyproj does the transform. The result is
verified by transforming back and comparing with the source eastings and
northings — see `--verify`, which is run automatically and aborts on failure.
Altitude is left to clampToGround; ground elevation is stated in the
description, because a KML altitude would imply a precision the DEM-derived
elevations do not have for every well.

Usage:
    python3 tools/make_well_kml.py            # write and verify
    python3 tools/make_well_kml.py --verify   # verify the existing file only
"""
from __future__ import annotations

__version__ = "1.0.0"  # Hollingham (2026) — 2026-09-09. First version (T-24, S6).

import sys
from pathlib import Path
from xml.sax.saxutils import escape

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import pandas as pd  # noqa: E402
import pyproj  # noqa: E402

from utils import paths  # noqa: E402

OUT_KML = paths.data_geo("well_locations.kml")
ROUNDTRIP_TOL_M = 0.01  # a transform that cannot round-trip to 1 cm is wrong


def _network_members() -> tuple[set[str], set[str]]:
    """Well keys of the reference and extended networks, from their own files."""
    ref = pd.read_csv(paths.INT_WELLS_REFERENCE, index_col=0, nrows=1)
    ext = pd.read_csv(paths.INT_WELLS_EXTENDED, index_col=0, nrows=1)
    norm = lambda cols: {str(c).strip().lower() for c in cols}
    return norm(ref.columns), norm(ext.columns)


def _locations() -> pd.DataFrame:
    loc = pd.read_csv(paths.INT_LOCATIONS)
    loc["key"] = loc["Match_ID"].astype(str).str.strip().str.lower()
    return loc


def build() -> tuple[str, pd.DataFrame]:
    ref_keys, ext_keys = _network_members()
    loc = _locations()

    lake = {k for k in loc["key"] if "llyn" in k or "rhos" in k}
    ref_keys -= lake
    ext_keys -= lake

    missing = (ref_keys | ext_keys) - set(loc["key"])
    if missing:
        raise SystemExit(f"ABORT: no coordinates for {sorted(missing)}")

    to_wgs = pyproj.Transformer.from_crs("EPSG:27700", "EPSG:4326", always_xy=True)
    rows = []
    for _, r in loc.iterrows():
        k = r["key"]
        group = ("reference" if k in ref_keys else
                 "extended" if k in ext_keys else
                 "lake" if k in lake else None)
        if group is None:
            continue
        lon, lat = to_wgs.transform(float(r["E"]), float(r["N"]))
        rows.append({"key": k, "label": str(r["Match_ID"]).strip().upper(),
                     "group": group, "E": float(r["E"]), "N": float(r["N"]),
                     "lon": lon, "lat": lat,
                     "ground": r.get("ground_elev_m"),
                     "in_forest": r.get("in_forest")})
    df = pd.DataFrame(rows)

    folders = [("reference", "Reference network dipwells",
                "Wells with records long enough for the clustering and modelling."),
               ("extended", "Extended network dipwells",
                "Additional dipwells, shorter or later records."),
               ("lake", "Lake gauge (not a dipwell)",
                "Llyn Rhos-Ddu lake-level gauge. Outside the classified dipwell network.")]

    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<kml xmlns="http://www.opengis.net/kml/2.2"><Document>',
           '<name>Newborough Warren groundwater monitoring network</name>',
           '<description>' + escape(
               "Dipwell and lake-gauge locations for the Newborough Warren dune aquifer "
               "study, Anglesey, Wales. Positions surveyed on OSGB36 / British National "
               "Grid (EPSG:27700) and transformed to WGS84 for this file. Generated by "
               "tools/make_well_kml.py from the committed pipeline outputs.") + '</description>']
    for gid, gname, gdesc in folders:
        sub = df[df["group"] == gid]
        if sub.empty:
            continue
        out.append(f"<Folder><name>{escape(gname)} ({len(sub)})</name>"
                   f"<description>{escape(gdesc)}</description>")
        for _, w in sub.sort_values("label").iterrows():
            bits = [f"British National Grid: {w['E']:.1f} E, {w['N']:.1f} N"]
            if pd.notna(w["ground"]):
                bits.append(f"Ground elevation: {float(w['ground']):.2f} m AOD")
            if gid != "lake" and pd.notna(w["in_forest"]):
                bits.append("Land cover: " + ("under canopy" if bool(w["in_forest"])
                                              else "open ground"))
            out.append(
                f"<Placemark><name>{escape(w['label'])}</name>"
                f"<description>{escape('; '.join(bits))}</description>"
                f"<Point><altitudeMode>clampToGround</altitudeMode>"
                f"<coordinates>{w['lon']:.8f},{w['lat']:.8f},0</coordinates>"
                f"</Point></Placemark>")
        out.append("</Folder>")
    out.append("</Document></kml>")
    return "\n".join(out) + "\n", df


def verify(path: Path) -> int:
    """Round-trip every placemark back to EPSG:27700 and compare with source."""
    import re
    xml = path.read_text(encoding="utf-8")
    pts = dict(zip(re.findall(r"<Placemark><name>([^<]+)</name>", xml),
                   re.findall(r"<coordinates>([^<]+)</coordinates>", xml)))
    loc = _locations()
    loc["label"] = loc["Match_ID"].astype(str).str.strip().str.upper()
    src = loc.set_index("label")
    to_bng = pyproj.Transformer.from_crs("EPSG:4326", "EPSG:27700", always_xy=True)
    worst, worst_at = 0.0, ""
    for label, coord in pts.items():
        lon, lat, _ = (float(v) for v in coord.split(","))
        e, n = to_bng.transform(lon, lat)
        row = src.loc[label]
        d = ((e - float(row["E"])) ** 2 + (n - float(row["N"])) ** 2) ** 0.5
        if d > worst:
            worst, worst_at = d, label
    print(f"  {len(pts)} placemark(s); worst round-trip error {worst*1000:.3f} mm at {worst_at}")
    if worst > ROUNDTRIP_TOL_M:
        print(f"  FAIL: round-trip error exceeds {ROUNDTRIP_TOL_M} m")
        return 1
    print("  round-trip OK")
    return 0


if __name__ == "__main__":
    if "--verify" in sys.argv:
        raise SystemExit(verify(OUT_KML))
    kml, df = build()
    OUT_KML.parent.mkdir(parents=True, exist_ok=True)
    OUT_KML.write_text(kml, encoding="utf-8")
    counts = df.groupby("group").size().to_dict()
    print(f"  wrote {OUT_KML.relative_to(REPO)}")
    print(f"  reference {counts.get('reference', 0)}, extended {counts.get('extended', 0)}, "
          f"lake gauge {counts.get('lake', 0)}  "
          f"(dipwell total {counts.get('reference', 0) + counts.get('extended', 0)})")
    raise SystemExit(verify(OUT_KML))
