#!/usr/bin/env python3
"""
manifest_lint — is the committed manifest what the live orchestrator produces?

WHY

  `pipeline_manifest.json` is the single source of truth for step and phase
  counts; every document quotes it rather than counting for itself. It is
  regenerated by any full pipeline run, which makes it vulnerable in a way the
  other committed outputs are not: **a run from a tree older than the one that
  last wrote it silently reverts it.**

  That happened on 2026-08-29. Script 40 was registered, the manifest was
  written with 51 steps, and a pipeline run from a tree predating the
  registration then rewrote it back to 50 with Script 40 absent. Nothing caught
  it. The manifest records `pipeline_version`, but the orchestrator version had
  not been bumped along with the registration, so a stale manifest and a current
  one were byte-comparable on the one field that could have told them apart.

  Two things follow, and this tool is the second:
    1. `build_manifest()` now warns at the point of write, on a downgrade and on
       a count change without a version bump.
    2. This lint compares the COMMITTED manifest against what the live
       `run_analysis.py` would produce right now — counts, phase total, and the
       orchestrator version — so a stale file cannot survive a `check_all`.

  GATING. A drifting manifest IS a failure: it is the number the documents cite.
  Rebuild it with `python3 run_analysis.py --manifest-only`.

__version__ : 1.0.0
"""
from __future__ import annotations

__version__ = "1.0.0"  # Hollingham (2026) — 2026-08-29. First issue, after a
#   stale manifest dropped a registered script and no check noticed.

import importlib.util
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "outputs" / "pipeline_manifest.json"

RED, GREEN, RESET = "\033[31m", "\033[32m", "\033[0m"


def _load_orchestrator():
    spec = importlib.util.spec_from_file_location("_ra", ROOT / "run_analysis.py")
    mod = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(ROOT))
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    if not MANIFEST.exists():
        print(f"  {RED}FAIL{RESET}  {MANIFEST.relative_to(ROOT)} is missing — "
              f"run: python3 run_analysis.py --manifest-only")
        return 1
    on_disk = json.loads(MANIFEST.read_text(encoding="utf-8"))
    ra = _load_orchestrator()
    live = ra.build_manifest(write=False)

    checks = [("pipeline_version", "orchestrator version"),
              ("total_registered", "registered steps"),
              ("total_phases", "phases")]
    bad = []
    for key, label in checks:
        if on_disk.get(key) != live.get(key):
            bad.append(f"{label}: committed {on_disk.get(key)!r}, live {live.get(key)!r}")
    for grp in ("by_tier", "by_exec"):
        for k, v in live.get(grp, {}).items():
            if on_disk.get(grp, {}).get(k) != v:
                bad.append(f"{grp}.{k}: committed "
                           f"{on_disk.get(grp, {}).get(k)!r}, live {v!r}")
    disk_scripts = {s.get("script") for s in on_disk.get("steps", [])}
    live_scripts = {s.get("script") for s in live.get("steps", [])}
    for missing in sorted(live_scripts - disk_scripts):
        bad.append(f"registered but absent from the committed manifest: {missing}")
    for extra in sorted(disk_scripts - live_scripts):
        bad.append(f"in the committed manifest but no longer registered: {extra}")

    if bad:
        print(f"  {RED}FAIL{RESET}  the committed manifest is not what the live "
              f"orchestrator produces:")
        for b in bad:
            print(f"          · {b}")
        print("        rebuild: python3 run_analysis.py --manifest-only")
        return 1
    print(f"  {GREEN}OK{RESET}    manifest matches the live orchestrator "
          f"(v{live['pipeline_version']}, {live['total_registered']} steps, "
          f"{live['total_phases']} phases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
