#!/usr/bin/env python3
"""
rule_gate_lint.py
=================
Which project rules have a gate, and does the matrix still describe the tree?

Why this exists.

  On 2026-09-21 a CLAUDE.md rule that had stood since the Methods Supplement
  existed ("do not send a reader to it") was broken six times in one morning by
  edits made in good faith, and found by the author reading the proof copy.
  Martin: "now I am worried we dont have adequate checks to ensure the project
  rules are followed." The rules live in prose (CLAUDE.md, the project box);
  the gates live in check_all.sh; nothing said which rules the gates covered.

  tools/rule_gate_matrix.csv is that statement: one row per rule, its source,
  how it is enforced, and the gate(s) that do it. `enforcement` is one of
    gated          a check_all gate fails when the rule is broken
    tool-refusal   a tool refuses the act (odt_edit, refresh_mirrors, wgit)
    by-design      the rule is a property of how a tool works
    partial        a gate covers part of the rule; the note says which part
    procedural     not lintable — a way of working
    none           nothing checks it; the note carries a PROPOSED gate or a
                   FINDING (a tool exists but is gated nowhere)

What it checks.

  1. Every tool named in `gate` exists as tools/<name>.py or tools/<name>.sh
     (or tools/<name>.csv for a register).
  2. A row marked `gated` names at least one tool that check_all.sh runs.
  3. Ids are unique and every row has a source, a rule and an enforcement.
  Any of those failing means the matrix no longer describes the tree, which
  is the rot a generated document suffers without a --check (CLAUDE.md §4d).
  The counts by enforcement are printed; `none` and `partial` are the work
  list, and are advisory here — this lint gates the MATRIX, not the rules.

Usage:
    python3 tools/rule_gate_lint.py             # check; non-zero if the matrix is wrong
    python3 tools/rule_gate_lint.py --quiet
    python3 tools/rule_gate_lint.py --write     # also render notes/findings/NRG_rule_gate_matrix.md
"""
from __future__ import annotations

import csv
import re
import sys
from collections import Counter
from pathlib import Path

__version__ = "1.0.0"  # Hollingham (2026) — 2026-09-21. First rule -> gate matrix.

REPO = Path(__file__).resolve().parents[1]
MATRIX = REPO / "tools/rule_gate_matrix.csv"
CHECK_ALL = REPO / "tools/check_all.sh"
OUT_MD = REPO / "notes/findings/NRG_rule_gate_matrix.md"
ENFORCEMENTS = {"gated", "tool-refusal", "by-design", "partial", "procedural", "none"}


def _rows() -> list[dict]:
    with MATRIX.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _tool_exists(name: str) -> bool:
    return any((REPO / "tools" / f"{name}{ext}").exists() for ext in (".py", ".sh", ".csv"))


def check(rows: list[dict], check_all_text: str) -> list[str]:
    faults = []
    ids = Counter(r["id"] for r in rows)
    for rid, n in ids.items():
        if n > 1:
            faults.append(f"duplicate id {rid}")
    for r in rows:
        rid = r["id"]
        if not (r["source"] and r["rule"]):
            faults.append(f"{rid}: source or rule empty")
        if r["enforcement"] not in ENFORCEMENTS:
            faults.append(f"{rid}: enforcement {r['enforcement']!r} not in {sorted(ENFORCEMENTS)}")
        gates = r["gate"].split()
        for g in gates:
            if not _tool_exists(g):
                faults.append(f"{rid}: gate {g!r} is not a tool under tools/")
        if r["enforcement"] == "gated":
            if not gates:
                faults.append(f"{rid}: gated but names no gate")
            elif not any(re.search(rf"tools/{re.escape(g)}\.(py|sh)", check_all_text) for g in gates):
                faults.append(f"{rid}: gated but none of {gates} is run by check_all.sh")
        if r["enforcement"] == "none" and not r["note"]:
            faults.append(f"{rid}: enforcement none needs a note (PROPOSED or FINDING)")
    return faults


def render(rows: list[dict]) -> str:
    counts = Counter(r["enforcement"] for r in rows)
    lines = ["# Project rules and the gates that check them",
             "",
             "Generated by `tools/rule_gate_lint.py --write` from `tools/rule_gate_matrix.csv` — "
             "edit the CSV, not this file. Rules are CLAUDE.md's and the project box's; gates are "
             "what `tools/check_all.sh` runs. `none` and `partial` are the work list.",
             "",
             "| enforcement | rules |", "|---|---|"]
    for k in ("gated", "tool-refusal", "by-design", "partial", "procedural", "none"):
        lines.append(f"| {k} | {counts.get(k, 0)} |")
    lines += ["", "| id | source | rule | enforcement | gate | note |", "|---|---|---|---|---|---|"]
    for r in rows:
        lines.append("| " + " | ".join(r[k].replace("|", "\\|") for k in
                                       ("id", "source", "rule", "enforcement", "gate", "note")) + " |")
    lines += ["", "## Findings (a tool exists but nothing runs it)", ""]
    lines += [f"- **{r['id']}** — {r['note']}" for r in rows if "FINDING" in r["note"]]
    lines += ["", "## Proposed gates", ""]
    lines += [f"- **{r['id']}** ({r['enforcement']}) — {r['note']}" for r in rows if "PROPOSED" in r["note"]]
    return "\n".join(lines) + "\n"


def main(argv) -> int:
    quiet = "--quiet" in argv
    rows = _rows()
    faults = check(rows, CHECK_ALL.read_text(encoding="utf-8"))
    counts = Counter(r["enforcement"] for r in rows)
    for f in faults:
        print(f"  FAIL {f}")
    if "--write" in argv:
        OUT_MD.parent.mkdir(parents=True, exist_ok=True)
        OUT_MD.write_text(render(rows), encoding="utf-8")
        print(f"  wrote {OUT_MD.relative_to(REPO)}")
    summary = ", ".join(f"{counts.get(k, 0)} {k}" for k in
                        ("gated", "tool-refusal", "by-design", "partial", "procedural", "none"))
    if faults:
        print(f"  rule_gate_lint: {len(faults)} fault(s) — the matrix no longer describes the tree")
        return 1
    if not quiet or counts.get("none", 0):
        print(f"  rule_gate_lint: {len(rows)} rules — {summary}; "
              f"{sum(1 for r in rows if 'FINDING' in r['note'])} finding(s), "
              f"{sum(1 for r in rows if 'PROPOSED' in r['note'])} proposed gate(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
