#!/usr/bin/env python3
"""
session_handover — generate the *state* half of a session handover.

Why this exists.

  A long assistant session ends one of two ways: deliberately, or by running out
  of context. The second is the common one, and it is the one that loses things.
  What survives a handover is exactly what was written to disk before it
  happened — so the handover cannot be a thing you remember to write at the end.

  This splits the handover in two:

    working/HANDOVER_BOOTSTRAP.md
                              the STABLE half — read order, standing constraints,
                              environment facts, how to pick up work. Changes
                              rarely, is written by hand, and is the first thing
                              a new session reads.

    working/updates/HANDOFF_<date>.md
                              the VOLATILE half — repository state, document
                              versions, open rulings, pipeline freshness. Changes
                              constantly, so it is GENERATED by this script and
                              never hand-written. A generated handover cannot be
                              out of date with the tree it describes, and cannot
                              be forgotten at the end of a session.

  The narrative — what was actually decided and why — belongs in neither. It goes
  in `working/updates/`, `working/changelogs/` and `working/DECISION_LOG.md` as
  it happens, which is what makes an abrupt ending survivable.

Usage:
    python3 tools/session_handover.py              # print to stdout
    python3 tools/session_handover.py --write      # write working/updates/HANDOFF_<date>.md
    python3 tools/session_handover.py --lag        # include the (slower) pipeline lag check
"""
from __future__ import annotations

__version__ = "1.6.0"  # Hollingham (2026) — 2026-08-28. First cut: the volatile
#   half of a handover, generated rather than remembered.

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PRIVATE_GIT = REPO / ".git-working"
REGISTER = REPO / "working" / "updates" / "NRG_WORK_REGISTER.md"
DECISIONS = REPO / "working" / "DECISION_LOG.md"
BOOTSTRAP = REPO / "working" / "HANDOVER_BOOTSTRAP.md"

DOC_DIRS = [REPO / "docs" / "report",
            REPO / "docs" / "papers" / "paper_1",
            REPO / "report_edits" / "odt"]

# Modules the pipeline needs that a sandboxed bridge often lacks. Probed rather
# than assumed, because "it imported last time" is not a property of this host.
PROBE = ["numpy", "pandas", "scipy", "statsmodels", "sklearn",
         "geopandas", "shapely", "pyproj", "fiona", "rasterio"]


def _run(cmd, cwd=REPO, timeout=120):
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        return 1, "", str(e)


def _git(*args, private=False, timeout=120):
    base = ["git", "--no-optional-locks"]
    if private:
        base += [f"--git-dir={PRIVATE_GIT}", f"--work-tree={REPO}"]
    return _run(base + list(args), timeout=timeout)


def _version_key(stem: str):
    """Sort key for a versioned document stem: ..._v1_9_61 -> (1, 9, 61)."""
    m = re.search(r"_v(\d+(?:_\d+)*)$", stem)
    if not m:
        return ()
    return tuple(int(p) for p in m.group(1).split("_"))


def section_repos() -> str:
    out = ["## Repository state", ""]
    for label, private in (("public `Newborough_Hydrology`", False),
                           ("private `Newborough_Hydrology_working`", True)):
        if private and not PRIVATE_GIT.exists():
            out += [f"**{label}** — `.git-working` not present.", ""]
            continue
        rc, status, err = _git("status", "--porcelain", private=private)
        if rc != 0:
            out += [f"**{label}** — could not read status: {err or 'unknown error'}", ""]
            continue
        lines = [l for l in status.splitlines() if l.strip()]
        mod = [l for l in lines if not l.startswith("??")]
        new = [l for l in lines if l.startswith("??")]
        _, head, _ = _git("log", "-1", "--format=%h %ad %s", "--date=short", private=private)
        out.append(f"**{label}** — head `{head}`")
        out.append(f"{len(mod)} modified, {len(new)} untracked.")
        if lines:
            out.append("")
            out += ["```"] + lines[:40] + (["… truncated"] if len(lines) > 40 else []) + ["```"]
        out.append("")
    out += ["**ODTs are gitignored** — document edits never appear in either status. "
            "The versions below are the only record of them.", ""]
    return "\n".join(out)


def section_documents() -> str:
    out = ["## Current document versions", ""]
    seen = []
    for d in DOC_DIRS:
        if not d.is_dir():
            continue
        families: dict[str, list[Path]] = {}
        for p in sorted(d.glob("*.odt")):
            if p.name.startswith(("~", ".")):
                continue
            base = re.sub(r"_v\d+(?:_\d+)*$", "", p.stem)
            families.setdefault(base, []).append(p)
        for base, paths in sorted(families.items()):
            versioned = [p for p in paths if _version_key(p.stem)]
            if versioned:
                latest = max(versioned, key=lambda p: _version_key(p.stem))
                extra = f"  ({len(versioned)} versions on disk)"
            else:
                latest = paths[0]
                extra = "  (unversioned — edited in place)"
            seen.append(f"- `{latest.relative_to(REPO)}`{extra}")
    out += seen or ["- none found"]
    out.append("")
    return "\n".join(out)


def section_open_rulings() -> str:
    """Register rows whose status cell says the row is open."""
    out = ["## Open rulings and unfinished rows", ""]
    if not REGISTER.is_file():
        return "\n".join(out + ["- register not found", ""])
    rows = []
    for line in REGISTER.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| **W"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if not cells:
            continue
        # The status cell is the last cell of a full-width row and is a short
        # word from a fixed vocabulary. Earlier this matched any cell CONTAINING
        # "open", which caught two closed rows whose narrative said "unblocked"
        # and "open-dune" — a row is open because its status says so, not because
        # its prose mentions it.
        status = cells[-1].lower().strip()
        subject = cells[1] if len(cells) > 1 else ""
        is_closed = subject.strip().startswith("~~")   # struck-through = closed
        looks_like_status = len(cells) >= 4 and len(status) <= 40
        if (looks_like_status and not is_closed
                and re.match(r"^(open|blocked|pending|todo|waiting)\b", status)):
            wid = re.match(r"\*\*(W\d+)\*\*", cells[0])
            wid = wid.group(1) if wid else cells[0][:8]
            subject = re.sub(r"\s+", " ", subject)
            rows.append(f"- **{wid}** — {subject[:240]}{'…' if len(subject) > 240 else ''}  \n"
                        f"  _status:_ {cells[-1]}")
    out += rows or ["- no rows currently marked open"]
    out.append("")
    return "\n".join(out)


def section_deferred() -> str:
    """Decisions deliberately left to a person, and still waiting.

    Martin, 2026-08-29: "Ideally I would like to be reminded of deferred
    decisions. These should be part of the daily report and work lists." The
    open-rulings section above reads the work register's status cells, which are
    hand-maintained and drift; this reads the decision log itself, so a deferral
    that never got a W row still surfaces.
    """
    out = ["## Deferred decisions — waiting on a person", ""]
    _rc, stdout, _err = _run(["python3", "tools/deferred_report.py"])
    body = re.sub(r"\x1b\[[0-9;]*m", "", stdout or "").rstrip()
    if not body:
        return "\n".join(out + ["- deferred_report did not run", ""])
    out.append("```")
    out.append(body)
    out.append("```")
    out.append("")
    return "\n".join(out)


def section_decisions() -> str:
    out = ["## Decision log", ""]
    if not DECISIONS.is_file():
        return "\n".join(out + ["- not found", ""])
    # Parse through context_for rather than with a second regex of our own. Two
    # parsers of one format drift, and this repo's characteristic defect is
    # exactly that: a derived artifact outliving agreement with its source.
    sys.path.insert(0, str(REPO / "tools"))
    from context_for import parse_entries          # noqa: E402
    ids = [(e["id"], e["title"], e["date"], e["status"]) for e in parse_entries()]
    active = [i for i in ids if i[3].strip().startswith("active")]
    if ids:
        other = len(ids) - len(active)
        out.append(f"{len(ids)} entries, {len(active)} active"
                   + (f", {other} superseded or retired" if other else "")
                   + f". Latest: **{ids[-1][0]}** — {ids[-1][1]}")
    else:
        out.append("- no entries parsed")
    out += ["",
            "**Search this before reopening any settled question.** The log exists because "
            "three decisions were re-litigated in one sitting after the reason for the "
            "original call had evaporated. The burden on reopening is to defeat the entry's "
            "`Revisit-if`, not to re-derive the answer.",
            ""]
    rc, _, _ = _run([sys.executable, "tools/decision_lint.py"])
    out += [f"`decision_lint`: **{'OK' if rc == 0 else 'FAILING'}**", ""]
    # Keep the one-line index in step with the log it indexes. Regenerating it
    # here means it cannot drift from the log between sessions.
    _run([sys.executable, "tools/context_for.py", "--index"])
    out += ["Scan `working/DECISION_INDEX.md` for the whole set in ~85 lines. "
            "**Do not read the log itself** — query it:", "",
            "```", 'python3 tools/context_for.py "report10 §4.2.3"',
            "python3 tools/context_for.py --changed", "```", ""]
    return "\n".join(out)


def section_environment() -> str:
    out = ["## This host", ""]
    out.append(f"- python `{sys.version.split()[0]}` at `{sys.executable}`")
    rc, ver, _ = _run(["pandoc", "--version"], timeout=30)
    out.append(f"- pandoc `{ver.splitlines()[0].split()[-1] if rc == 0 and ver else 'absent'}`")
    ok, missing = [], []
    for m in PROBE:
        rc, _, _ = _run([sys.executable, "-c", f"import {m}"], timeout=60)
        (ok if rc == 0 else missing).append(m)
    out.append(f"- importable: {', '.join(f'`{m}`' for m in ok) or 'none'}")
    if missing:
        out.append(f"- **NOT importable: {', '.join(f'`{m}`' for m in missing)}** — "
                   f"every `src/` script depending on these cannot run here.")
    out += ["",
            "**The environment-adequacy control.** Before trusting any rerun from a host "
            "that is not the recorded pipeline environment, reproduce that script's "
            "committed output first. Byte-identical means the rerun is trustworthy *for "
            "that script* and no further.", ""]
    return "\n".join(out)


def section_tier0() -> str:
    """Measure the read-every-session set, so its growth is visible rather than felt.

    D-080 caps Tier 0. A cap nobody measures is a wish, and this is the file best
    placed to measure it — it is regenerated every time the set changes.
    """
    out = ["## Tier 0 budget", ""]
    index = REPO / "working" / "DECISION_INDEX.md"
    latest = sorted((REPO / "working" / "updates").glob("HANDOFF_*.md"))
    # The hand-written narrative note joined the read order on 2026-08-29 and was
    # not being counted, so this measured a Tier 0 that no longer existed. A gate
    # that measures the wrong set is worse than none: it reported "over budget"
    # while omitting the largest member.
    note = sorted((REPO / "working" / "updates").glob("HANDOVER_NOTE_*.md"))
    members = [BOOTSTRAP, latest[-1] if latest else None,
               note[-1] if note else None, index]
    total, rows = 0, []
    for m in members:
        if m and m.is_file():
            n = len(m.read_text(encoding="utf-8").splitlines())
            total += n
            rows.append(f"- `{m.relative_to(REPO)}` — {n} lines")
    rows.append(f"- **total {total} lines**")
    out += rows + [""]
    # The index costs about one line per decision and grows with the log; that is
    # the right price. The prose is what must be held down.
    prose = total - (len(index.read_text(encoding="utf-8").splitlines())
                     if index.is_file() else 0)
    # 600 lines of prose, ~8k tokens. The original 250 was set on 2026-08-29
    # before the narrative note existed and was a guess, not a measurement; it
    # was tight enough that the honest response to breaching it would have been
    # to delete useful orientation. Re-set against what Tier 0 actually holds,
    # with the principle unchanged: nothing joins without something leaving.
    BUDGET = 600
    out.append(f"Prose portion (excluding the one-line-per-decision index): "
               f"**{prose} lines**, against a D-080 budget of **{BUDGET}**. "
               + ("Within budget." if prose <= BUDGET else
                  f"**Over by {prose - BUDGET}** — something must leave Tier 0 "
                  "before anything joins it."))
    out.append("")
    return "\n".join(out)


def section_lag() -> str:
    out = ["## Pipeline freshness", ""]
    rc, so, se = _run([sys.executable, "tools/export_lag.py", "--no-pages"], timeout=600)
    body = (so or se).strip()
    tail = body.splitlines()[-25:]
    out += ["```"] + tail + ["```", ""]
    return "\n".join(out)


def build(include_lag: bool) -> str:
    today = date.today().isoformat()
    parts = [
        f"# Session handover — {today}",
        "",
        "**Generated by `tools/session_handover.py`. Do not hand-edit — regenerate it.**",
        "",
        f"The stable half of the handover is `{BOOTSTRAP.relative_to(REPO)}`; read that "
        "first. This file is only the state of the tree at the moment it was written.",
        "",
        "---",
        "",
        section_repos(),
        section_documents(),
        section_open_rulings(),
        section_deferred(),
        section_decisions(),
        section_environment(),
        section_tier0(),
    ]
    if include_lag:
        parts.append(section_lag())
    parts += [
        "---",
        "",
        "## Before finishing a session",
        "",
        "1. Every finding written to `working/updates/`, every code change to a "
        "`working/changelogs/CHANGELOG_delta_*` file, every judgement call to "
        "`working/DECISION_LOG.md`. These are appended as they happen, not at the end.",
        "2. A register row in `working/updates/NRG_WORK_REGISTER.md` — with the status "
        "cell saying **open** if a ruling is owed, so this script surfaces it.",
        "3. Regenerate this file: `python3 tools/session_handover.py --write` "
        "(which refreshes `working/DECISION_INDEX.md` with it).",
        "",
    ]
    return "\n".join(parts)


def main(argv):
    include_lag = "--lag" in argv
    text = build(include_lag)
    if "--write" in argv:
        dest = REPO / "working" / "updates" / f"HANDOFF_{date.today().isoformat()}.md"
        dest.write_text(text, encoding="utf-8")
        print(f"  WROTE  {dest.relative_to(REPO)}  ({len(text.splitlines())} lines)")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
