#!/usr/bin/env python3
"""
session_handover — generate the *state* half of a session handover, and GATE the
records a session must leave behind.

Why this exists.

  A long assistant session ends one of two ways: deliberately, or by running out
  of context. The second is the common one, and it is the one that loses things.
  What survives a handover is exactly what was written to disk before it
  happened — so the handover cannot be a thing you remember to write at the end.

  This splits the handover in two:

    working/HANDOVER_BOOTSTRAP.md
                              the STABLE half — read order, standing constraints,
                              environment facts, how to pick up work. Changes
                              rarely, is written by hand, and is the first thing
                              a new session reads.

    working/updates/HANDOFF_<date>.md
                              the VOLATILE half — repository state, document
                              versions, open rulings, pipeline freshness. Changes
                              constantly, so it is GENERATED by this script and
                              never hand-written. A generated handover cannot be
                              out of date with the tree it describes, and cannot
                              be forgotten at the end of a session.

    working/updates/HANDOVER_NOTE.md
                              the NARRATIVE half — one rolling file, newest entry
                              first, one dated `## YYYY-MM-DD — title` entry per
                              session, as long as that session's work warrants
                              (D-150): what was done, what is owed, which
                              D-numbers. Replaces the free-form
                              HANDOVER_cowork_<date>.md documents (D-143): a
                              6,000-word handover is excellent and is not read.
                              Tier 0's TOTAL budget is the binding constraint.

  The reasoning — what was actually decided and why — belongs in none of these.
  It goes in `working/changelogs/` and `working/DECISION_LOG.md` as it happens,
  where `context_for.py` can find it by subject.

Why --check exists (D-143).

  On 2026-08-28 this tool, HANDOVER_BOOTSTRAP.md and context_for.py were built
  so that a new session would start from a generated, budgeted Tier 0. HANDOFF
  files exist for 08-28, 08-29 and 08-30 — and then stop. Every session after
  wrote a free-form handover in a different format, DECISION_INDEX.md sat at
  D-110 while the log reached D-142, and check_all was green throughout,
  because no gate read any of these records. A rule that lives only in prose,
  an artefact nothing consumes, and a verdict that depends on neither: the same
  shape as D-102 (output_lag) and D-133 (input provenance), applied to the
  project's own records. --check makes the records a gate. If it fails, the fix
  is to write the record, never to skip the check.

Usage:
    python3 tools/session_handover.py              # print the state to stdout
    python3 tools/session_handover.py --write      # write working/updates/HANDOFF_<date>.md
    python3 tools/session_handover.py --lag        # include the (slower) pipeline lag check
    python3 tools/session_handover.py --check      # GATE: exit 1 if the records are stale
    python3 tools/session_handover.py --selftest   # exercise the --check detectors
"""
from __future__ import annotations

__version__ = "2.0.1"  # Hollingham (2026).
#   2.0.1 (2026-09-07): detector 2 measures the HANDOFF against max(its header
#     timestamp, the newest private commit that carried a HANDOFF). Without
#     this a private commit bundling the fresh HANDOFF with changelogs was
#     itself "newer than the HANDOFF" and the gate failed on its first L14 run
#     (17:11, seconds after the records commit). A commit that ships the HANDOFF
#     is the records commit; only what lands AFTER it can make it stale.
#   2.0.0 (2026-09-07): --check gate (D-143). Five detectors: DECISION_INDEX
#     count vs DECISION_LOG; newest HANDOFF older than the newest substantive
#     commit; HANDOVER_NOTE.md missing an entry for the newest commit day, or an
#     entry over NOTE_LONG_ENTRY (advisory since D-150); script commits in the
#     last CHANGELOG_WINDOW_DAYS
#     with no CHANGELOG_delta naming them; Tier-0 prose over budget. HANDOFF
#     header now carries an ISO timestamp so age is measured against commits,
#     not against the filename's day. Tier 0 reads the rolling HANDOVER_NOTE.md
#     (the dated HANDOVER_NOTE_<date>.md is superseded). --selftest.
#   1.6.0 (2026-08-28): first cut — the volatile half of a handover, generated
#     rather than remembered.

import re
import subprocess
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PRIVATE_GIT = REPO / ".git-working"
UPDATES = REPO / "working" / "updates"
REGISTER = UPDATES / "NRG_WORK_REGISTER.md"
DECISIONS = REPO / "working" / "DECISION_LOG.md"
INDEX = REPO / "working" / "DECISION_INDEX.md"
BOOTSTRAP = REPO / "working" / "HANDOVER_BOOTSTRAP.md"
NOTE = UPDATES / "HANDOVER_NOTE.md"
CHANGELOGS = REPO / "working" / "changelogs"

# --check parameters. Named here, not scattered, so the gate's tolerances are
# one lookup away when they need arguing with.
# ADVISORY, not a gate (D-150). It was a hard cap until 2026-09-09, when a
# thirteen-batch day hit it three times in one session and each collision cost a
# round of compression that removed detail the changelogs had to carry instead.
# Martin's ruling: "long days get long entries." The real cost of Tier 0 is its
# TOTAL length, and TIER0_PROSE_BUDGET already gates that — a per-entry cap was a
# proxy for it, and a proxy that punishes a productive day is the wrong shape.
# Entries over this are still printed, so growth stays visible rather than felt.
NOTE_LONG_ENTRY = 40         # per dated entry in HANDOVER_NOTE.md — advisory
TIER0_PROSE_BUDGET = 600     # lines, excluding the one-line-per-decision index (D-080)
CHANGELOG_WINDOW_DAYS = 3    # script commits this recent must have a changelog
CHANGELOG_LEAD_DAYS = 2      # a changelog may precede its commit by this much
# Records the gate itself produces; a commit that touches only these does not
# make the HANDOFF stale, or the gate would fail the moment its output was committed.
RECORD_PATHS = ("working/updates/HANDOFF_", "working/updates/HANDOVER_NOTE.md",
                "working/DECISION_INDEX.md")
CODE_SUFFIXES = (".py", ".sh")
CODE_ROOTS = ("src/", "tools/", "run_analysis.py", "run_09_scraping.py", "run_10_clearfell.py")

DOC_DIRS = [REPO / "docs" / "report",
            REPO / "docs" / "papers" / "paper_1",
            REPO / "report_edits" / "odt"]

# Modules the pipeline needs that a sandboxed bridge often lacks. Probed rather
# than assumed, because "it imported last time" is not a property of this host.
PROBE = ["numpy", "pandas", "scipy", "statsmodels", "sklearn",
         "geopandas", "shapely", "pyproj", "fiona", "rasterio"]


def _run(cmd, cwd=REPO, timeout=120):
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return r.returncode, r.stdout.strip(), r.stderr.strip()
    except (subprocess.TimeoutExpired, FileNotFoundError) as e:
        return 1, "", str(e)


def _git(*args, private=False, timeout=120):
    base = ["git", "--no-optional-locks"]
    if private:
        base += [f"--git-dir={PRIVATE_GIT}", f"--work-tree={REPO}"]
    return _run(base + list(args), timeout=timeout)


def _version_key(stem: str):
    """Sort key for a versioned document stem: ..._v1_9_61 -> (1, 9, 61)."""
    m = re.search(r"_v(\d+(?:_\d+)*)$", stem)
    if not m:
        return ()
    return tuple(int(p) for p in m.group(1).split("_"))


# ---------------------------------------------------------------- state sections

def section_repos() -> str:
    out = ["## Repository state", ""]
    for label, private in (("public `Newborough_Hydrology`", False),
                           ("private `Newborough_Hydrology_working`", True)):
        if private and not PRIVATE_GIT.exists():
            out += [f"**{label}** — `.git-working` not present.", ""]
            continue
        rc, status, err = _git("status", "--porcelain", private=private)
        if rc != 0:
            out += [f"**{label}** — could not read status: {err or 'unknown error'}", ""]
            continue
        lines = [l for l in status.splitlines() if l.strip()]
        mod = [l for l in lines if not l.startswith("??")]
        new = [l for l in lines if l.startswith("??")]
        _, head, _ = _git("log", "-1", "--format=%h %ad %s", "--date=short", private=private)
        out.append(f"**{label}** — head `{head}`")
        out.append(f"{len(mod)} modified, {len(new)} untracked.")
        if lines:
            out.append("")
            out += ["```"] + lines[:40] + (["… truncated"] if len(lines) > 40 else []) + ["```"]
        out.append("")
    out += ["**ODTs are gitignored** — document edits never appear in either status. "
            "The versions below are the only record of them.", ""]
    return "\n".join(out)


def section_documents() -> str:
    out = ["## Current document versions", ""]
    seen = []
    for d in DOC_DIRS:
        if not d.is_dir():
            continue
        families: dict[str, list[Path]] = {}
        for p in sorted(d.glob("*.odt")):
            if p.name.startswith(("~", ".")):
                continue
            base = re.sub(r"_v\d+(?:_\d+)*$", "", p.stem)
            families.setdefault(base, []).append(p)
        for base, paths in sorted(families.items()):
            versioned = [p for p in paths if _version_key(p.stem)]
            if versioned:
                latest = max(versioned, key=lambda p: _version_key(p.stem))
                extra = f"  ({len(versioned)} versions on disk)"
            else:
                latest = paths[0]
                extra = "  (unversioned — edited in place)"
            seen.append(f"- `{latest.relative_to(REPO)}`{extra}")
    out += seen or ["- none found"]
    out.append("")
    return "\n".join(out)


def section_open_rulings() -> str:
    """Register rows whose status cell says the row is open."""
    out = ["## Open rulings and unfinished rows", ""]
    if not REGISTER.is_file():
        return "\n".join(out + ["- register not found", ""])
    rows = []
    for line in REGISTER.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| **W"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if not cells:
            continue
        # The status cell is the last cell of a full-width row and is a short
        # word from a fixed vocabulary. Earlier this matched any cell CONTAINING
        # "open", which caught two closed rows whose narrative said "unblocked"
        # and "open-dune" — a row is open because its status says so, not because
        # its prose mentions it.
        status = cells[-1].lower().strip()
        subject = cells[1] if len(cells) > 1 else ""
        is_closed = subject.strip().startswith("~~")   # struck-through = closed
        looks_like_status = len(cells) >= 4 and len(status) <= 40
        if (looks_like_status and not is_closed
                and re.match(r"^(open|blocked|pending|todo|waiting)\b", status)):
            wid = re.match(r"\*\*(W\d+)\*\*", cells[0])
            wid = wid.group(1) if wid else cells[0][:8]
            subject = re.sub(r"\s+", " ", subject)
            rows.append(f"- **{wid}** — {subject[:240]}{'…' if len(subject) > 240 else ''}  \n"
                        f"  _status:_ {cells[-1]}")
    out += rows or ["- no rows currently marked open"]
    out.append("")
    return "\n".join(out)


def section_deferred() -> str:
    """Decisions deliberately left to a person, and still waiting.

    Martin, 2026-08-29: "Ideally I would like to be reminded of deferred
    decisions. These should be part of the daily report and work lists." The
    open-rulings section above reads the work register's status cells, which are
    hand-maintained and drift; this reads the decision log itself, so a deferral
    that never got a W row still surfaces.
    """
    out = ["## Deferred decisions — waiting on a person", ""]
    _rc, stdout, _err = _run(["python3", "tools/deferred_report.py"])
    body = re.sub(r"\x1b\[[0-9;]*m", "", stdout or "").rstrip()
    if not body:
        return "\n".join(out + ["- deferred_report did not run", ""])
    out.append("```")
    out.append(body)
    out.append("```")
    out.append("")
    return "\n".join(out)


def _decision_entries():
    # Parse through context_for rather than with a second regex of our own. Two
    # parsers of one format drift, and this repo's characteristic defect is
    # exactly that: a derived artifact outliving agreement with its source.
    sys.path.insert(0, str(REPO / "tools"))
    from context_for import parse_entries          # noqa: E402
    return parse_entries()


def section_decisions() -> str:
    out = ["## Decision log", ""]
    if not DECISIONS.is_file():
        return "\n".join(out + ["- not found", ""])
    ids = [(e["id"], e["title"], e["date"], e["status"]) for e in _decision_entries()]
    active = [i for i in ids if i[3].strip().startswith("active")]
    if ids:
        other = len(ids) - len(active)
        out.append(f"{len(ids)} entries, {len(active)} active"
                   + (f", {other} superseded or retired" if other else "")
                   + f". Latest: **{ids[-1][0]}** — {ids[-1][1]}")
    else:
        out.append("- no entries parsed")
    out += ["",
            "**Search this before reopening any settled question.** The log exists because "
            "three decisions were re-litigated in one sitting after the reason for the "
            "original call had evaporated. The burden on reopening is to defeat the entry's "
            "`Revisit-if`, not to re-derive the answer.",
            ""]
    rc, _, _ = _run([sys.executable, "tools/decision_lint.py"])
    out += [f"`decision_lint`: **{'OK' if rc == 0 else 'FAILING'}**", ""]
    # Keep the one-line index in step with the log it indexes. Regenerating it
    # here means it cannot drift from the log between sessions — and --check
    # fails if it has.
    _run([sys.executable, "tools/context_for.py", "--index"])
    out += ["Scan `working/DECISION_INDEX.md` for the whole set. "
            "**Do not read the log itself** — query it:", "",
            "```", 'python3 tools/context_for.py "report10 §4.2.3"',
            "python3 tools/context_for.py --changed", "```", ""]
    return "\n".join(out)


def section_environment() -> str:
    out = ["## This host", ""]
    out.append(f"- python `{sys.version.split()[0]}` at `{sys.executable}`")
    rc, ver, _ = _run(["pandoc", "--version"], timeout=30)
    out.append(f"- pandoc `{ver.splitlines()[0].split()[-1] if rc == 0 and ver else 'absent'}`")
    ok, missing = [], []
    for m in PROBE:
        rc, _, _ = _run([sys.executable, "-c", f"import {m}"], timeout=60)
        (ok if rc == 0 else missing).append(m)
    out.append(f"- importable: {', '.join(f'`{m}`' for m in ok) or 'none'}")
    if missing:
        out.append(f"- **NOT importable: {', '.join(f'`{m}`' for m in missing)}** — "
                   f"every `src/` script depending on these cannot run here.")
    out += ["",
            "**The environment-adequacy control.** Before trusting any rerun from a host "
            "that is not the recorded pipeline environment, reproduce that script's "
            "committed output first. Byte-identical means the rerun is trustworthy *for "
            "that script* and no further.", ""]
    return "\n".join(out)


def _latest_handoff() -> Path | None:
    files = sorted(UPDATES.glob("HANDOFF_*.md"))
    return files[-1] if files else None


def tier0_measure() -> tuple[int, int, list[str]]:
    """(total lines, prose lines, per-member rows). The index is excluded from prose."""
    members = [BOOTSTRAP, _latest_handoff(), NOTE if NOTE.is_file() else None, INDEX]
    total, rows = 0, []
    for m in members:
        if m and m.is_file():
            n = len(m.read_text(encoding="utf-8").splitlines())
            total += n
            rows.append(f"- `{m.relative_to(REPO)}` — {n} lines")
    index_lines = len(INDEX.read_text(encoding="utf-8").splitlines()) if INDEX.is_file() else 0
    return total, total - index_lines, rows


def section_tier0() -> str:
    """Measure the read-every-session set, so its growth is visible rather than felt.

    D-080 caps Tier 0. A cap nobody measures is a wish, and this is the file best
    placed to measure it — it is regenerated every time the set changes.
    """
    out = ["## Tier 0 budget", ""]
    total, prose, rows = tier0_measure()
    out += rows + [f"- **total {total} lines**", ""]
    # The index costs about one line per decision and grows with the log; that is
    # the right price. The prose is what must be held down. 600 lines of prose,
    # ~8k tokens, re-set 2026-08-29 against what Tier 0 actually holds, with the
    # principle unchanged: nothing joins without something leaving.
    out.append(f"Prose portion (excluding the one-line-per-decision index): "
               f"**{prose} lines**, against a D-080 budget of **{TIER0_PROSE_BUDGET}**. "
               + ("Within budget." if prose <= TIER0_PROSE_BUDGET else
                  f"**Over by {prose - TIER0_PROSE_BUDGET}** — something must leave Tier 0 "
                  "before anything joins it."))
    out.append("")
    return "\n".join(out)


def section_lag() -> str:
    out = ["## Pipeline freshness", ""]
    rc, so, se = _run([sys.executable, "tools/export_lag.py", "--no-pages"], timeout=600)
    body = (so or se).strip()
    tail = body.splitlines()[-25:]
    out += ["```"] + tail + ["```", ""]
    return "\n".join(out)


def build(include_lag: bool) -> str:
    now = datetime.now().astimezone()
    parts = [
        f"# Session handover — {now.date().isoformat()}",
        "",
        f"**Generated by `tools/session_handover.py` at {now.isoformat(timespec='seconds')}. "
        "Do not hand-edit — regenerate it.**",
        "",
        f"The stable half of the handover is `{BOOTSTRAP.relative_to(REPO)}`; read that "
        f"first. The narrative half is `{NOTE.relative_to(REPO)}` (newest entry first). "
        "This file is only the state of the tree at the moment it was written.",
        "",
        "---",
        "",
        section_repos(),
        section_documents(),
        section_open_rulings(),
        section_deferred(),
        section_decisions(),
        section_environment(),
        section_tier0(),
    ]
    if include_lag:
        parts.append(section_lag())
    parts += [
        "---",
        "",
        "## Before finishing a session",
        "",
        "1. Every code change to a `working/changelogs/CHANGELOG_delta_*` file, every "
        "judgement call to `working/DECISION_LOG.md`, findings to `working/updates/`. "
        "These are appended as they happen, not at the end.",
        "2. A register row in `working/updates/NRG_WORK_REGISTER.md` — with the status "
        "cell saying **open** if a ruling is owed, so this script surfaces it.",
        f"3. A dated entry at the TOP of `{NOTE.relative_to(REPO)}` — as long as the "
        "session's work warrants: what was done, what is owed, which D-numbers (or 'none').",
        "4. Regenerate this file: `python3 tools/session_handover.py --write` "
        "(which refreshes `working/DECISION_INDEX.md` with it), then "
        "`python3 tools/session_handover.py --check` must say OK.",
        "",
    ]
    return "\n".join(parts)


# ------------------------------------------------------------------- the gate

def _parse_iso(s: str) -> datetime | None:
    try:
        return datetime.fromisoformat(s.strip())
    except ValueError:
        return None


def handoff_timestamp(path: Path) -> datetime:
    """When the HANDOFF was generated. Header timestamp (2.0.0+); older files
    carry only a date in the filename and are taken as the end of that day."""
    head = path.read_text(encoding="utf-8", errors="replace")[:400] if path.is_file() else ""
    m = re.search(r"at (\d{4}-\d{2}-\d{2}T[0-9:]{8}[+-]\d{2}:\d{2})", head)
    if m and (ts := _parse_iso(m.group(1))):
        return ts
    m = re.search(r"HANDOFF_(\d{4}-\d{2}-\d{2})", path.name)
    d = date.fromisoformat(m.group(1)) if m else date.min
    return datetime.combine(d, datetime.max.time()).astimezone()


def newest_handoff_commit() -> datetime | None:
    """Timestamp of the newest private commit that carried a HANDOFF file."""
    if not PRIVATE_GIT.exists():
        return None
    rc, out, _ = _git("log", "-1", "--format=%cI", "--", "working/updates/HANDOFF_*.md",
                      private=True)
    return _parse_iso(out) if rc == 0 and out else None


def newest_substantive_commit() -> tuple[datetime | None, str]:
    """Newest commit on either repo that touched something other than the
    records this gate produces. Returns (timestamp, 'repo hash subject')."""
    best, label = None, ""
    excl = [f":(exclude,glob){p}*" for p in RECORD_PATHS]
    for name, private in (("public", False), ("private", True)):
        if private and not PRIVATE_GIT.exists():
            continue
        rc, out, _ = _git("log", "-1", "--format=%cI|%h %s", "--", ".", *excl, private=private)
        if rc != 0 or not out:
            continue
        ts_s, _, rest = out.partition("|")
        ts = _parse_iso(ts_s)
        if ts and (best is None or ts > best):
            best, label = ts, f"{name} {rest}"
    return best, label


def note_entries(text: str) -> list[tuple[date | None, str, int]]:
    """[(date, heading, line count)] for each `## YYYY-MM-DD — title` entry."""
    entries, cur, count = [], None, 0
    for line in text.splitlines():
        m = re.match(r"^## (\d{4}-\d{2}-\d{2})\b(.*)$", line)
        if m:
            if cur is not None:
                entries.append((*cur, count))
            try:
                d = date.fromisoformat(m.group(1))
            except ValueError:
                d = None
            cur, count = (d, line.strip()), 0
        elif cur is not None:
            count += 1
    if cur is not None:
        entries.append((*cur, count))
    return entries


def script_commits(window_days: int) -> list[tuple[date, str, list[str]]]:
    """[(commit date, 'hash subject', [changed code basenames])] within the window."""
    since = (date.today() - timedelta(days=window_days)).isoformat()
    rc, out, _ = _git("log", f"--since={since}", "--format=@@%cs|%h %s", "--name-only",
                      "--", *CODE_ROOTS)
    commits, cur = [], None
    for line in out.splitlines():
        if line.startswith("@@"):
            ds, _, rest = line[2:].partition("|")
            cur = (date.fromisoformat(ds), rest, [])
            commits.append(cur)
        elif cur and line.strip():
            p = line.strip()
            if p.endswith(CODE_SUFFIXES) and ".bak" not in p:
                cur[2].append(Path(p).name)
    return [c for c in commits if c[2]]


def changelog_mentions(stem: str, lo: date, hi: date) -> bool:
    """Does any CHANGELOG_delta dated in [lo, hi] name this script?"""
    pats = [re.escape(stem)]
    m = re.match(r"^(\d{2}[a-z]?)_", stem)        # 43_ranwell_sites -> 'Script 43'
    if m:
        pats.append(r"[Ss]cript\s+0?" + re.escape(m.group(1).lstrip("0")) + r"\b")
    rx = re.compile("|".join(pats))
    for f in CHANGELOGS.glob("CHANGELOG_delta_*.md"):
        dm = re.search(r"(\d{4}-\d{2}-\d{2})", f.name)
        if not dm:
            continue
        d = date.fromisoformat(dm.group(1))
        if lo <= d <= hi and rx.search(f.read_text(encoding="utf-8", errors="replace")):
            return True
    return False


def check(verbose: bool = True) -> int:
    """The gate. Prints one line per detector; returns 1 if any fails."""
    fails = []
    say = print if verbose else (lambda *a, **k: None)

    # 1. Index agrees with the log.
    n_log = len(_decision_entries()) if DECISIONS.is_file() else 0
    n_idx = len(re.findall(r"^\| \*\*D-\d+\*\*", INDEX.read_text(encoding="utf-8"), re.M)) \
        if INDEX.is_file() else 0
    if n_log != n_idx:
        fails.append(f"DECISION_INDEX has {n_idx} entries, DECISION_LOG {n_log} — "
                     "run: python3 tools/context_for.py --index")
    say(f"  {'ok   ' if n_log == n_idx else 'FAIL '} decision index {n_idx} / log {n_log}")

    # 2. HANDOFF newer than the newest substantive commit.
    ho = _latest_handoff()
    commit_ts, commit_label = newest_substantive_commit()
    if ho is None:
        fails.append("no working/updates/HANDOFF_*.md — run: python3 tools/session_handover.py --write")
        say("  FAIL  no HANDOFF found")
    else:
        # Written-at, or committed-at, whichever is later: the commit that ships
        # the HANDOFF is the records commit and cannot make it stale (2.0.1).
        ref = handoff_timestamp(ho)
        hc = newest_handoff_commit()
        if hc and hc > ref:
            ref = hc
        if commit_ts and ref < commit_ts:
            fails.append(f"{ho.name} predates the newest commit ({commit_label}) — "
                         "run: python3 tools/session_handover.py --write (nrg_git.sh "
                         "option 2 does this before the private commit)")
            say(f"  FAIL  {ho.name} older than {commit_label}")
        else:
            say(f"  ok    {ho.name} current against {commit_label or 'no commits'}")

    # 3. HANDOVER_NOTE has an entry for the newest commit day, entries within length.
    if not NOTE.is_file():
        fails.append(f"{NOTE.relative_to(REPO)} missing")
        say("  FAIL  HANDOVER_NOTE.md missing")
    else:
        ents = note_entries(NOTE.read_text(encoding="utf-8"))
        dates = [e[0] for e in ents if e[0]]
        newest = max(dates) if dates else None
        need = commit_ts.astimezone().date() if commit_ts else None
        if not ents:
            fails.append("HANDOVER_NOTE.md has no `## YYYY-MM-DD — title` entries")
            say("  FAIL  HANDOVER_NOTE.md has no dated entries")
        elif need and (newest is None or newest < need):
            fails.append(f"HANDOVER_NOTE.md newest entry {newest} predates the newest commit "
                         f"day {need} — add a dated entry at the top")
            say(f"  FAIL  HANDOVER_NOTE newest entry {newest} < commit day {need}")
        else:
            say(f"  ok    HANDOVER_NOTE newest entry {newest}")
        # Advisory since D-150: reported so growth is visible, never failed.
        # TIER0_PROSE_BUDGET below is what actually binds.
        for h, n in [(h, n) for _, h, n in ents if n > NOTE_LONG_ENTRY]:
            say(f"  note  {n}-line entry (over {NOTE_LONG_ENTRY}, advisory): {h[:56]}")
        if ents and ents != sorted(ents, key=lambda e: e[0] or date.min, reverse=True):
            fails.append("HANDOVER_NOTE.md entries are not newest-first")
            say("  FAIL  HANDOVER_NOTE entries not newest-first")

    # 4. Recent script commits have a changelog naming them.
    uncovered = []
    for d, label, names in script_commits(CHANGELOG_WINDOW_DAYS):
        missing = [n for n in names
                   if not changelog_mentions(Path(n).stem, d - timedelta(days=CHANGELOG_LEAD_DAYS),
                                             date.today())]
        if missing:
            uncovered.append((label, missing))
    if uncovered:
        for label, missing in uncovered:
            fails.append(f"no CHANGELOG_delta names {', '.join(missing)} (commit {label})")
            say(f"  FAIL  {label}: {', '.join(missing)}")
    else:
        say(f"  ok    every script commit in the last {CHANGELOG_WINDOW_DAYS} days has a changelog")

    # 5. Tier-0 prose budget.
    _total, prose, _rows = tier0_measure()
    if prose > TIER0_PROSE_BUDGET:
        fails.append(f"Tier 0 prose {prose} lines over the {TIER0_PROSE_BUDGET} budget (D-080)")
    say(f"  {'ok   ' if prose <= TIER0_PROSE_BUDGET else 'FAIL '} Tier 0 prose {prose}/{TIER0_PROSE_BUDGET} lines")

    if fails:
        print("session_handover --check: FAIL")
        for f in fails:
            print(f"    - {f}")
        return 1
    print("session_handover --check: OK")
    return 0


def selftest() -> int:
    """Exercise the parsers the gate relies on. A green gate proves nothing if
    its detectors have stopped detecting."""
    bad = []
    ents = note_entries("# t\n\n## 2026-09-07 — a\nx\ny\n\n## 2026-09-06 — b\nz\n")
    if [(e[0].isoformat(), e[2]) for e in ents] != [("2026-09-07", 3), ("2026-09-06", 1)]:
        bad.append(f"note_entries: {ents}")
    ents2 = note_entries("## 2026-09-06 — b\n## 2026-09-07 — a\n")
    if ents2 == sorted(ents2, key=lambda e: e[0], reverse=True):
        bad.append("newest-first detector accepted an out-of-order note")
    fake = ("# Session handover — 2026-09-07\n\n**Generated by `tools/session_handover.py` "
            "at 2026-09-07T15:40:12+01:00. Do not**")
    m = re.search(r"at (\d{4}-\d{2}-\d{2}T[0-9:]{8}[+-]\d{2}:\d{2})", fake)
    if not (m and _parse_iso(m.group(1))):
        bad.append("HANDOFF timestamp regex does not match its own header")
    if not re.search(r"[Ss]cript\s+0?43\b", "Script 43 v1.0.0 emits"):
        bad.append("Script NN mention pattern")
    # The gate must be able to fail: an unreachable HANDOFF date must read as stale.
    ancient = UPDATES / ("HANDOFF_2000-01-01" + ".md")   # built, not a literal: docref_lint reads literals as citations
    if not handoff_timestamp(ancient) < datetime.now().astimezone():
        bad.append("handoff_timestamp fallback did not read a filename date")
    if bad:
        print("session_handover --selftest: FAIL")
        for b in bad:
            print(f"    - {b}")
        return 1
    print("session_handover --selftest: OK")
    return 0


def main(argv):
    if "--selftest" in argv:
        return selftest()
    if "--check" in argv:
        return check(verbose="--quiet" not in argv)
    include_lag = "--lag" in argv
    text = build(include_lag)
    if "--write" in argv:
        dest = UPDATES / f"HANDOFF_{date.today().isoformat()}.md"
        dest.write_text(text, encoding="utf-8")
        print(f"  WROTE  {dest.relative_to(REPO)}  ({len(text.splitlines())} lines)")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
