#!/usr/bin/env python3
"""
ship_regen_lint.py
==================
Does the ship rebuild every derived artefact that check_all gates?

Why this exists.

  On 2026-09-30 three ships in a row failed on red gates that were not
  defects: a mirror stamped after it was cut, a register nobody regenerated,
  a published PDF the ship rebuilt one step AFTER the gate that fails on it.
  Each gate was right; each was checking something the ship could have rebuilt
  itself. D-213 makes that the ship's contract: `working/nrg_git.sh`
  `ship_regenerate()` rebuilds every derived artefact in dependency order
  before `check_all`, so a red gate afterwards is a person's defect.

  A contract nobody measures is a wish (D-080's lesson). This lint reads both
  sides - the `--check` / `--gate` gates in tools/check_all.sh and the calls in
  ship_regenerate() (and the shell functions it names) - and fails when a gate
  on derived state has no regenerate call, or a regenerate call has no gate.

What counts.

  A gate is a `python3 tools/<x>.py ... --check` or `--gate` line in
  check_all.sh, plus export_lag (the published-PDF gate, which has no --check
  flag). Gates that check something a person writes, the environment, or the
  pipeline's own consistency are declared in EXEMPT with the reason, and the
  lint refuses an exemption that names a tool check_all no longer runs.

  Regeneration is a `tools/<x>.py` or `tools/<x>.sh` call inside
  ship_regenerate() or inside a bash function it calls (refresh_mirror,
  build_docs_pdfs, sync_index_counts, build_master_pdf ...), resolved one level.

Usage:
    python3 tools/ship_regen_lint.py            # report; exit 1 on a mismatch
    python3 tools/ship_regen_lint.py --quiet    # verdict line only
    python3 tools/ship_regen_lint.py --selftest

  The private store (working/) is absent from a public clone; the lint then
  reports SKIPPED and exits 0 - it cannot judge a ship it cannot see (the T-27 /
  T-30 lesson: a check that errors in a public clone gates nothing).
"""
from __future__ import annotations

__version__ = "1.0.0"  # Hollingham (2026) - 2026-09-30. D-213.

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CHECK_ALL = REPO / "tools" / "check_all.sh"
NRG_GIT = REPO / "working" / "nrg_git.sh"

# gate tool -> why the ship does not regenerate what it checks
EXEMPT = {
    "env_audit":             "checks the machine, not an artefact",
    "freeze_requirements":   "the recorded environment; refreshed deliberately, never by a ship",
    "pipeline_lint":         "the pipeline's own consistency (defaults, deps, run id, literals)",
    "table_gen":             "document tables are regenerated by a person with --force, then read",
    "starmath_log":          "the formula log is written by odt_edit as formulas change",
    "output_lag":            "a script newer than its outputs needs a pipeline RUN, not a rebuild",
    "input_provenance_lint": "outputs against committed inputs: a pipeline run, not a rebuild",
}
# gates written without --check
EXTRA_GATES = {"export_lag": "the published PDFs (build_pdfs.sh inside build_docs_pdfs)"}
# what a regenerate call must be named, when the tool's writer is not tools/<gate>.py
REGEN_ALIAS = {
    "export_lag":       {"build_pdfs", "build_docs_pdfs"},
    "refresh_mirrors":  {"refresh_mirrors", "refresh_mirror"},
    "session_handover": {"session_handover"},
}


def gates(text: str) -> dict[str, str]:
    """tool name -> the check_all line that gates it."""
    out: dict[str, str] = {}
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("#"):
            continue
        m = re.search(r"tools/([a-z_0-9]+)\.(?:py|sh)\b([^|&]*)", s)
        if not m:
            continue
        tool, args = m.group(1), m.group(2)
        if re.search(r"--(check|gate)\b", args) and "--selftest" not in args:
            out.setdefault(tool, s)
        if tool in EXTRA_GATES:
            out.setdefault(tool, s)
    return out


def _function_body(text: str, name: str) -> str:
    m = re.search(rf"^{re.escape(name)}\(\)\s*\{{\n(.*?)^\}}", text, re.S | re.M)
    return m.group(1) if m else ""


def regenerates(text: str) -> set[str]:
    """Tool names (tools/<x>.py|.sh) and bash function names reachable from ship_regenerate()."""
    body = _function_body(text, "ship_regenerate")
    if not body:
        return set()
    seen: set[str] = set()
    funcs = set(re.findall(r"^\s*([a-z_]+)\s*(?:\|\||$|>|;)", body, re.M))
    funcs |= set(re.findall(r"^\s*([a-z_]+)\s*$", body, re.M))
    for f in sorted(funcs):
        fb = _function_body(text, f)
        if fb:
            seen.add(f)
            body += "\n" + fb
            # one more level (build_docs_pdfs -> build_master_pdf)
            for g in set(re.findall(r"^\s*([a-z_]+)\s*(?:\|\||$|;)", fb, re.M)):
                gb = _function_body(text, g)
                if gb:
                    seen.add(g)
                    body += "\n" + gb
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("#"):
            continue
        for m in re.finditer(r"tools/([a-z_0-9]+)\.(?:py|sh)\b", s):
            seen.add(m.group(1))
        m = re.search(r"for\s+t\s+in\s+(.+?);\s*do", s)
        if m:
            seen |= set(m.group(1).replace("\\", " ").split())
    # a for-loop over names split across lines
    m = re.search(r"for\s+t\s+in\s+(.*?)\s*;\s*do", body, re.S)
    if m:
        seen |= set(m.group(1).replace("\\", " ").split())
    return seen


def evaluate(check_text: str, git_text: str, exempt: dict[str, str] | None = None) -> tuple[list[str], list[str]]:
    exempt = EXEMPT if exempt is None else exempt
    g = gates(check_text)
    r = regenerates(git_text)
    faults, notes = [], []
    for tool in sorted(g):
        if tool in exempt:
            notes.append(f"  exempt  {tool:24s} {exempt[tool]}")
            continue
        names = REGEN_ALIAS.get(tool, {tool})
        if names & r:
            notes.append(f"  ok      {tool:24s} regenerated by the ship")
        else:
            faults.append(f"gate without a regenerate: {tool} ({g[tool][:70]}) - add it to ship_regenerate() or to EXEMPT with the reason")
    for tool in sorted(exempt):
        if tool not in g:
            faults.append(f"EXEMPT names {tool}, which check_all.sh no longer gates - remove the row")
    if not _function_body(git_text, "ship_regenerate"):
        faults.append("working/nrg_git.sh has no ship_regenerate() function")
    return faults, notes


def selftest() -> int:
    ca = "python3 tools/build_x_ledger.py --check || rc=1\npython3 tools/env_audit.py --gate || rc=1\n"
    ng = "ship_regenerate(){\n  python3 tools/build_x_ledger.py\n}\n"
    ex = {"env_audit": "test"}
    f, _ = evaluate(ca, ng, ex)
    assert not f, f
    f, _ = evaluate(ca + "python3 tools/build_y_ledger.py --check || rc=1\n", ng, ex)
    assert any("build_y_ledger" in x for x in f), f
    f, _ = evaluate(ca, "do_ship(){\n:\n}\n", ex)
    assert any("no ship_regenerate" in x for x in f), f
    print("ship_regen_lint --selftest: OK")
    return 0


def main(argv: list[str]) -> int:
    if "--selftest" in argv:
        return selftest()
    quiet = "--quiet" in argv
    if not NRG_GIT.is_file():
        print("ship_regen_lint: SKIPPED - working/nrg_git.sh is not in this checkout (public clone)")
        return 0
    faults, notes = evaluate(CHECK_ALL.read_text(encoding="utf-8"), NRG_GIT.read_text(encoding="utf-8"))
    if not quiet:
        for n in notes:
            print(n)
    for f in faults:
        print(f"  FAULT   {f}")
    n_ok = sum(1 for n in notes if n.strip().startswith("ok"))
    n_ex = sum(1 for n in notes if n.strip().startswith("exempt"))
    print(f"ship_regen_lint: {'FAIL' if faults else 'OK'} - {n_ok} gated artefact(s) regenerated by the ship, {n_ex} exempt, {len(faults)} fault(s)")
    return 1 if faults else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
