r"""
====================================================================================
GROUNDWATER FORECASTING MODELS (forecasting_models.py)
====================================================================================
Purpose:
  Takes the monthly cluster-averaged output from LCSC3.py and performs three
  complementary analyses for manuscript publication:

    SECTION 1 — Mechanistic State-Space Equations
        Fits the multivariate state-space model to each block (Eastern, Western, Forest):
                Δhₜ = β₁Pₜ − β₂PETₜ − β₃hₜ₋₁
        Regression is performed without an intercept (OLS through the origin) to
        enforce physical mass balance: when all forcing terms are zero, the change
        in water-table elevation must also be zero.

    SECTION 2 — Peak Flood Transfer Functions
        Constructs empirical transfer functions for the Eastern, Western, and Forest
        blocks (when available) that predict maximum winter water level from:
        h_peak = β₁·P_winter + β₂·h_min + c
    where h_min is the preceding summer drought minimum (April–September) and
    P_winter is cumulative precipitation over October–March.
    Data are indexed by Hydrological Year (starting 1 October) to keep each
    recharge cycle intact.

  SECTION 3 — Critical Rainfall Thresholds (Management Tool)
    Algebraically inverts the Section 1 equations (setting winter PET = 0)
    to derive the critical rainfall needed to raise the water table to flood
    surface from any given antecedent depth:
        P_flood = (h_gap + β₃·h_prev) / β₁
    Outputs ready-to-use LibreOffice and LaTeX expressions for each cluster.

    SECTION 4 — Summer Drought Transfer Functions
        Fits empirical OLS models for each block predicting the summer
    drought minimum (h_min_summer) from antecedent winter storage and
    cumulative summer rain:
        h_min_summer = β₁·P_summer + β₂·h_max_winter + c
    Complements Section 2 by characterising the drying leg of the annual
    water-table cycle.

Dependencies:
    - 03_regional_averages.csv  (generated by 03_state_space_model.py)
  - pandas, statsmodels

Outputs:
  - outputs/11_forecasting_thresholds/11_forecast_01_results.txt

Excluded clusters:
    C5 (coastal) and C6 (lake-buffered) are excluded from Section 1 mechanistic state-space equations
    because its boundary-condition behaviour violates free-draining assumptions.
    All block transfer-function sections (2 and 4) and mechanistic equations (1, 3)
    use the block time-series exported by LCSC03 (Eastern, Western, Forest) when present.
====================================================================================
"""

import sys as _sys, os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__))); del _sys, _os
from utils.paths import (
    make_all_dirs,
    INT_REGIONAL_AVG,
    OUT_11_RESULTS,
    OUT_11_TABLE6_WINTER,
    OUT_11_TABLE7_SUMMER,
    OUT_11_TABLE8_THRESHOLDS,
)
import os
import sys
import re
from io import IOBase
from pathlib import Path
from typing import Optional
import pandas as pd
import statsmodels.api as sm


# ====================================================================================
# TEE: mirror stdout to a file
# ====================================================================================
class _Tee:
    """
    Context manager that writes every print() call to both the terminal
    (original stdout) and a plain-text file simultaneously.

    Usage::
        with _Tee(path):
            run_models()   # all output goes to terminal AND file
    """
    def __init__(self, filepath: Path):
        self._filepath: Path              = filepath
        self._orig_out                    = sys.stdout
        self._fh: Optional[IOBase]        = None

    def write(self, data: str) -> None:
        self._orig_out.write(data)
        if self._fh:
            self._fh.write(data)

    def flush(self) -> None:
        self._orig_out.flush()
        if self._fh:
            self._fh.flush()

    def __enter__(self):
        self._fh = open(self._filepath, 'w', encoding='utf-8')
        sys.stdout = self
        return self

    def __exit__(self, *_):
        sys.stdout = self._orig_out
        self._fh.close()
        print(f"\n[OUTPUT] Results transcript saved → {self._filepath}")

# ====================================================================================
# PATH CONFIGURATION
# ====================================================================================



make_all_dirs()
OUT_FILE  = OUT_11_RESULTS   # plain-text transcript of all results

# ====================================================================================
# CONFIGURATION
# ====================================================================================
MASTER_FILE = INT_REGIONAL_AVG

# C5 (coastal) and C6 (lake-buffered) are excluded from the mechanistic state-space equations.
EXCLUDED_CLUSTERS = {'C5', 'C6'}

SUMMER_MONTHS  = [4, 5, 6, 7, 8, 9]    # Apr–Sep  (drought / recession season)
WINTER_MONTHS  = [10, 11, 12, 1, 2, 3]  # Oct–Mar  (recharge / flood season)
MIN_VALID_MONTHS = 3                     # minimum months per season to include a hydrological year


# ====================================================================================
# HELPERS
# ====================================================================================
def load_data(filepath: 'str | Path') -> pd.DataFrame:
    """Load 03_regional_averages.csv and validate its structure."""
    if not os.path.exists(filepath):
        sys.exit(
            f"\n[ERROR] Required input file not found: '{filepath}'\n"
            "        Please run 03_state_space_model.py first to generate this file.\n"
        )
    df = pd.read_csv(filepath, index_col='Date', parse_dates=True)
    required = {'P_mm', 'PET_mm', 'Western_Block', 'Eastern_Block'}
    missing = required - set(df.columns)
    if missing:
        sys.exit(
            f"\n[ERROR] '{filepath}' is missing expected columns: {missing}\n"
            "        Please re-run 03_state_space_model.py to regenerate the file.\n"
        )
    return df


def sep(title: str, width: int = 70) -> str:
    """Return a formatted section header string."""
    return f"\n{'=' * width}\n{title}\n{'=' * width}"


# ====================================================================================
# SECTION 1: MECHANISTIC STATE-SPACE EQUATIONS
# ====================================================================================
def run_state_space(df: pd.DataFrame) -> dict:
    """
    Fit the state-space model for each qualifying cluster column.

    Model (no intercept — physical mass-balance constraint):
        Δhₜ = β₁·Pₜ − β₂·PETₜ − β₃·hₜ₋₁

    PET and h_prev are sign-inverted before fitting so that all three
    reported β coefficients emerge as positive values in the equation.

    Returns:
        results_dict: {cluster_name: {beta1, beta2, beta3, r2, n}}
    """
    print(sep("SECTION 1: MECHANISTIC STATE-SPACE EQUATIONS  (Δh = β₁P − β₂PET − β₃h_prev)"))
    print("  OLS without intercept — enforces physical mass balance (zero forcing → zero change)\n")

    # Macro-block/cluster mapping for print labels
    cluster_labels = {
        'C1': 'C1: Eastern Block Lake',
        'C2': 'C2: Eastern Block Mature Dune',
        'C3': 'C3: Western Block Mature Dune',
        'C4': 'C4: Forest',
        'C5': 'C5: Coastal',
        'C6': 'C6: Lake'
    }
    cluster_cols = sorted(
        c for c in df.columns
        if re.fullmatch(r'C\d+', c) and c not in EXCLUDED_CLUSTERS
    )
    results_dict = {}

    if not cluster_cols:
        print("  [WARNING] No qualifying cluster columns found. Check EXCLUDED_CLUSTERS setting.")
        return results_dict

    for col in cluster_cols:
        # Build a working frame with only the columns we need
        work = df[[col, 'P_mm', 'PET_mm']].copy()
        work['h_prev']  = work[col].shift(1)
        work['Delta_h'] = work[col] - work['h_prev']
        work = work.dropna(subset=['Delta_h', 'P_mm', 'PET_mm', 'h_prev'])

        if len(work) < 30:
            print(f"  {cluster_labels.get(col, col)}: Insufficient data ({len(work)} rows) — skipped.")
            continue

        # Invert PET and h_prev so β₂ and β₃ are reported as positive quantities
        X = pd.DataFrame({
            'P_mm':   work['P_mm'],
            'PET_mm': -work['PET_mm'],   # sign inversion
            'h_prev': -work['h_prev'],   # sign inversion
        }, index=work.index)

        model = sm.OLS(work['Delta_h'], X).fit()   # no intercept (through origin)
        b1, b2, b3 = model.params['P_mm'], model.params['PET_mm'], model.params['h_prev']
        pb1 = model.pvalues['P_mm']
        pb2 = model.pvalues['PET_mm']
        pb3 = model.pvalues['h_prev']

        print(
            f"  {cluster_labels.get(col, col)}:  Δh = ({b1:.4f}·P) − ({b2:.4f}·PET) − ({b3:.4f}·h_prev)"
            f"   |  R² = {model.rsquared:.3f}   n = {len(work)}"
        )
        print(
            f"        p-values:  P = {pb1:.4f}   PET = {pb2:.4f}   h_prev = {pb3:.4f}"
        )

        results_dict[col] = {
            'beta1': b1,
            'beta2': b2,
            'beta3': b3,
            'r2':    model.rsquared,
            'n':     len(work),
        }

    print(f"\n  Excluded from mechanistic model: {', '.join(sorted(EXCLUDED_CLUSTERS))}"
          f"  (boundary-condition clusters — see script header)")

    return results_dict


# ====================================================================================
# SECTION 2: PEAK FLOOD TRANSFER FUNCTIONS
# ====================================================================================
def run_peak_forecasting(df: pd.DataFrame) -> None:
    """
    Fit empirical peak-flood transfer functions for available blocks
    (Western, Eastern, and Forest where provided).

    For each Hydrological Year (Oct 1 – Sep 30):
        h_min    = minimum water level over Apr–Sep  (summer drought memory)
        P_winter = cumulative precipitation over Oct–Mar
        h_peak   = maximum water level over Oct–Mar  (target variable)

    Regression (OLS with intercept):
        h_peak = β₁·P_winter + β₂·h_min + c

    Note on block handling:
        Uses exported block columns from LCSC03 directly. Western_Block and
        Eastern_Block are expected; Forest and Coastal are included when available.
    """
    print(sep("SECTION 2: PEAK FLOOD TRANSFER FUNCTIONS  (h_peak = β₁·P_winter + β₂·h_min + c)"))
    print("  OLS with intercept | Hydrological year: Oct 1 – Sep 30")
    print("  Macro-blocks: Eastern Block (C1 & C2), Western Block (C3), Forest (C4).\n")
    print("  Note: C6 is a boundary outlier (lake/tidal) and is excluded from standard unconfined assumptions.\n")

    # Defensive: ensure index is DatetimeIndex and sorted
    df = df.copy()
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()

    # Tag each row with its Hydrological Year
    # Oct/Nov/Dec → belongs to the year starting that October (year + 1 label)
    # Jan–Sep     → belongs to the year that started the previous October
    df['Hydro_Year'] = df.index.year + (df.index.month >= 10).astype(int)

    # Use exported macro-block columns when present.
    blocks = [block for block in ['Western_Block', 'Eastern_Block', 'Forest'] if block in df.columns]
    table6_rows = []
    for block in blocks:
        if block not in df.columns:
            print(f"  {block}: column not found in data — skipped.")
            continue

        yearly_data = []

        for year, subset in df.groupby('Hydro_Year'):
            # Drop NaNs for this block only to avoid cross-column contamination
            summer = subset[subset.index.month.isin(SUMMER_MONTHS)][[block]].dropna()
            winter = subset[subset.index.month.isin(WINTER_MONTHS)][[block, 'P_mm']].dropna()

            # Require MIN_VALID_MONTHS per season for a reliable min/max
            if len(summer) >= MIN_VALID_MONTHS and len(winter) >= MIN_VALID_MONTHS:
                yearly_data.append({
                    'h_peak':   winter[block].max(),
                    'h_min':    summer[block].min(),
                    'P_winter': winter['P_mm'].sum(),
                })

        hydro_df = pd.DataFrame(yearly_data).dropna()

        if len(hydro_df) < 5:
            print(f"  {block}: Insufficient hydrological years ({len(hydro_df)}) — skipped.")
            continue

        X     = sm.add_constant(hydro_df[['P_winter', 'h_min']])
        model = sm.OLS(hydro_df['h_peak'], X).fit()

        c   = model.params['const']
        b1  = model.params['P_winter']
        b2  = model.params['h_min']
        pc  = model.pvalues['const']
        pb1 = model.pvalues['P_winter']
        pb2 = model.pvalues['h_min']

        print(f"  {block}:")
        print(f"    h_peak = ({b1:.5f}·P_winter) + ({b2:.3f}·h_min) {'+' if c >= 0 else '-'} {abs(c):.3f}")
        print(f"    R² = {model.rsquared:.3f}   |   n = {len(hydro_df)} hydrological years")
        print(f"    p-values:  P_winter = {pb1:.4f}   h_min = {pb2:.4f}   intercept = {pc:.4f}")
        print()

        table6_rows.append({
            'Block': block,
            'beta_1_P_winter': float(b1),
            'beta_2_h_min': float(b2),
            'intercept': float(c),
            'R2': float(model.rsquared),
            'n_hydrological_years': int(len(hydro_df)),
            'p_value_P_winter': float(pb1),
            'p_value_h_min': float(pb2),
            'p_value_intercept': float(pc),
            'equation': f"h_peak = ({b1:.5f}*P_winter) + ({b2:.3f}*h_min) {'+' if c >= 0 else '-'} {abs(c):.3f}",
        })

    pd.DataFrame(table6_rows).to_csv(OUT_11_TABLE6_WINTER, index=False)


# ====================================================================================
# SECTION 3: CRITICAL RAINFALL THRESHOLD EQUATIONS
# ====================================================================================
def run_critical_flood_thresholds(results_dict: dict) -> None:
    """
    Inverts the Section 1 state-space equations to solve for P_flood.

    Derivation (winter PET ≈ 0 — standard hydrological simplification for
    peak saturation events when evaporative demand is negligible):

        Δh = β₁·P − β₃·h_prev         (PET term dropped)
        Setting Δh = h_gap  (deficit to flood surface from current h_prev):
        P_flood = (h_gap + β₃·h_prev) / β₁

    Because the coefficients are taken directly from results_dict, the
    management equations update automatically if the source data changes.
    """
    print(sep("SECTION 3: CRITICAL RAINFALL THRESHOLD EQUATIONS  (P_flood)"))
    print("  Algebraically inverted from Section 1 state-space mechanics.")
    print("  Assumes winter PET = 0 (defensible for peak-saturation events).\n")

    # Only fitted, non-excluded clusters (ordered by cluster ID)
    target_clusters = sorted(
        (cluster for cluster in results_dict if cluster not in EXCLUDED_CLUSTERS),
        key=lambda name: (0, int(name[1:])) if name.startswith('C') and name[1:].isdigit() else (1, name),
    )

    cluster_labels = {
        'C1': 'C1: Eastern Block Lake',
        'C2': 'C2: Eastern Block Mature Dune',
        'C3': 'C3: Western Block Mature Dune',
        'C4': 'C4: Forest',
        'C5': 'C5: Coastal',
        'C6': 'C6: Lake'
    }
    table8_rows = []
    for cluster in target_clusters:
        if cluster not in results_dict:
            print(f"  {cluster_labels.get(cluster, cluster)}: no fitted parameters available — skipped.")
            continue

        b1 = results_dict[cluster]['beta1']
        b3 = results_dict[cluster]['beta3']

        # Special label for C4
        if cluster == 'C4':
            print(f"  C4: Forest Management Tool:")
        else:
            print(f"  {cluster_labels.get(cluster, cluster)} Management Tool:")
        print(f"    LibreOffice: =(h_gap + ({b3:.4f} * h_prev)) / {b1:.4f}")
        print(f"    LaTeX:       P_{{flood}} = \\frac{{h_{{gap}} + ({b3:.4f} \\cdot h_{{prev}})}}{{{b1:.4f}}}")
        print()

        table8_rows.append({
            'Cluster': cluster,
            'Label': cluster_labels.get(cluster, cluster),
            'beta_1': float(b1),
            'beta_3': float(b3),
            'libreoffice_formula': f"=(h_gap + ({b3:.4f} * h_prev)) / {b1:.4f}",
            'latex_formula': f"P_{{flood}} = \\frac{{h_{{gap}} + ({b3:.4f} \\cdot h_{{prev}})}}{{{b1:.4f}}}",
        })
    print("Note: Threshold equations are reported for all fitted non-boundary clusters (C1-C4).\n")

    pd.DataFrame(table8_rows).to_csv(OUT_11_TABLE8_THRESHOLDS, index=False)

# ====================================================================================
# SECTION 4: SUMMER DROUGHT TRANSFER FUNCTIONS
# ====================================================================================
def run_summer_drought_forecasting(df: pd.DataFrame) -> None:
    """
    Fit empirical summer drought transfer functions for available blocks
    (Western, Eastern, and Forest where provided).

    For each Hydrological Year (Oct 1 – Sep 30):
        h_max_winter = maximum water level over Oct–Mar (antecedent winter storage)
        P_summer     = cumulative precipitation over Apr–Sep
        h_min_summer = minimum water level over Apr–Sep (target drought variable)

    Regression (OLS with intercept):
        h_min_summer = β₁·P_summer + β₂·h_max_winter + c
    """
    print(sep("SECTION 4: SUMMER DROUGHT TRANSFER FUNCTIONS  (h_min = β₁·P_summer + β₂·h_max_winter + c)"))
    print("  OLS with intercept | Hydrological year: Oct 1 – Sep 30")
    print("  Predicting summer minimum from antecedent winter peak and summer rain.\n")

    df = df.copy()
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()
    df['Hydro_Year'] = df.index.year + (df.index.month >= 10).astype(int)

    blocks = [block for block in ['Western_Block', 'Eastern_Block', 'Forest'] if block in df.columns]
    table7_rows = []
    for block in blocks:
        if block not in df.columns:
            continue

        yearly_data = []

        for year, subset in df.groupby('Hydro_Year'):
            winter = subset[subset.index.month.isin(WINTER_MONTHS)][[block]].dropna()
            summer = subset[subset.index.month.isin(SUMMER_MONTHS)][[block, 'P_mm']].dropna()

            if len(summer) >= MIN_VALID_MONTHS and len(winter) >= MIN_VALID_MONTHS:
                yearly_data.append({
                    'h_min_summer': summer[block].min(),
                    'h_max_winter': winter[block].max(),
                    'P_summer':     summer['P_mm'].sum(),
                })

        hydro_df = pd.DataFrame(yearly_data).dropna()

        if len(hydro_df) < 5:
            print(f"  {block}: Insufficient hydrological years ({len(hydro_df)}) — skipped.")
            continue

        X     = sm.add_constant(hydro_df[['P_summer', 'h_max_winter']])
        model = sm.OLS(hydro_df['h_min_summer'], X).fit()

        c   = model.params['const']
        b1  = model.params['P_summer']
        b2  = model.params['h_max_winter']
        pc  = model.pvalues['const']
        pb1 = model.pvalues['P_summer']
        pb2 = model.pvalues['h_max_winter']

        print(f"  {block}:")
        print(f"    h_min_summer = ({b1:.5f}·P_summer) + ({b2:.3f}·h_max_winter) {'+' if c >= 0 else '-'} {abs(c):.3f}")
        print(f"    R² = {model.rsquared:.3f}   |   n = {len(hydro_df)} hydrological years")
        print(f"    p-values:  P_summer = {pb1:.4f}   h_max_winter = {pb2:.4f}   intercept = {pc:.4f}")
        print()

        table7_rows.append({
            'Block': block,
            'beta_1_P_summer': float(b1),
            'beta_2_h_max_winter': float(b2),
            'intercept': float(c),
            'R2': float(model.rsquared),
            'n_hydrological_years': int(len(hydro_df)),
            'p_value_P_summer': float(pb1),
            'p_value_h_max_winter': float(pb2),
            'p_value_intercept': float(pc),
            'equation': f"h_min_summer = ({b1:.5f}*P_summer) + ({b2:.3f}*h_max_winter) {'+' if c >= 0 else '-'} {abs(c):.3f}",
        })

    pd.DataFrame(table7_rows).to_csv(OUT_11_TABLE7_SUMMER, index=False)

# ====================================================================================
# ENTRY POINT
# ====================================================================================
def run_models() -> None:
    print("\nLoading input data...")
    df = load_data(MASTER_FILE)
    print(f"  [OK] {len(df)} monthly rows loaded | "
          f"Columns: {', '.join(df.columns.tolist())}")

    results_dict = run_state_space(df)
    run_peak_forecasting(df)
    run_summer_drought_forecasting(df)
    run_critical_flood_thresholds(results_dict)

    print("\n" + "=" * 70)
    print("  Analysis complete.")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    make_all_dirs()
    with _Tee(OUT_FILE):
        run_models()