r"""
====================================================================================
GROUNDWATER FORECASTING MODELS (11_forecasting_thresholds.py)
====================================================================================
Purpose:
  Takes the monthly cluster-averaged output from 03_state_space_model.py and
  performs four complementary analyses supporting Section 3.6 of Hollingham
  (2026):

    SECTION 1 — Mechanistic State-Space Equations
        Loads cluster-centroid lag-1 SSM coefficients from Script 03's
        mechanistic coefficients table (03_03_cluster_mechanistic_coefficients.csv)
        and converts from m/m to m/mm for downstream use. Reports coefficients
        and p-values for the transcript. Previously fitted its own lag-0 OLS
        on cluster-average hydrographs; superseded by Script 03's lag-1 fits.

    SECTION 2 — Peak Flood Transfer Functions
        Constructs empirical transfer functions for the Eastern, Western, and
        Forest blocks that predict maximum winter water level from:
            h_peak = β₁·P_winter + β₂·h_min + c
        where h_min is the preceding summer drought minimum (April-September)
        and P_winter is cumulative precipitation over October-March.
        Data are indexed by Hydrological Year (starting 1 October) to keep
        each recharge cycle intact.

    SECTION 3 — Critical Rainfall Thresholds (Management Tool)  [REVISED 2026-04]
        Iterates the Section 1 monthly recurrence forward from the September
        summer minimum to each cluster's historical peak-of-record month, with
        rainfall scaled by a multiplier λ and PET held at RAF Valley monthly
        climatology. Solves the resulting closed form for λ:
            λ = (h_target - h_0·αⁿ + β₂·S_E) / (β₁·S_P)
            P_flood = λ · Σ P̄ᵢ
        where α = 1 - β₃, S_P and S_E are drainage-weighted climatology sums,
        and n is the cluster-specific horizon length.

        Supersedes the earlier single-step formulation
            P_flood = (h_gap + β₃·h_prev) / β₁
        which neglected winter PET (~30% of winter atmospheric demand at RAF
        Valley) and implicitly treated the six-month recharge season as a
        single SSM timestep. The old formulation is retained in the output
        CSV under column "P_flood_old_single_step_mm" for continuity.

        See revised Section 3.6.3 of Hollingham (2026) for full derivation.

    SECTION 4 — Summer Drought Transfer Functions
        Fits empirical OLS models for each block predicting the summer drought
        minimum (h_min_summer) from antecedent winter storage and cumulative
        summer rainfall:
            h_min_summer = β₁·P_summer + β₂·h_max_winter + c
        Complements Section 2 by characterising the drying leg of the annual
        water-table cycle.

Dependencies:
    - 03_regional_averages.csv  (generated by 03_state_space_model.py)
    - pandas, statsmodels

Outputs:
    - outputs/11_forecasting_thresholds/11_forecast_01_results.txt
    - Table 6: winter transfer functions  (11_forecast_winter_transfer_functions.csv)
    - Table 7: summer transfer functions  (11_forecast_summer_transfer_functions.csv)
    - Table 8: P_flood threshold equations (11_forecast_pflood_threshold_equations.csv)

Cluster scope (k=5 partition):
    All five clusters participate in mechanistic and block-transfer sections.
    The original old-k=6 EXCLUDED_CLUSTERS set (C5 tidal, C6 lake-buffered)
    targeted small-n / unreliable groups; under the current partition those
    were cleaned out at the partition level, so EXCLUDED_CLUSTERS is empty.
    Block columns are produced by 03_state_space_model.py via BLOCK_MAP:
    Lake_Edge (C1), Eastern_Block (C2), Western_Block (C3), Forest (C4),
    Coastal_Forest (C5).
====================================================================================
"""

import sys as _sys, os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__))); del _sys, _os
from utils.paths import (
    make_all_dirs,
    INT_REGIONAL_AVG,
    INT_CLUSTER_PEAK_MONTHS,
    OUT_03_MECHANISTIC_TABLE,
    OUT_11_RESULTS,
    OUT_11_TABLE6_WINTER,
    OUT_11_TABLE7_SUMMER,
    OUT_11_TABLE8_THRESHOLDS,
)
from utils.config import CLUSTER_LABELS
import os
import sys
from io import IOBase
from pathlib import Path
from typing import Optional
import pandas as pd
import statsmodels.api as sm


# ====================================================================================
# TEE: mirror stdout to a file
# ====================================================================================
class _Tee:
    """
    Context manager that writes every print() call to both the terminal
    (original stdout) and a plain-text file simultaneously.

    Usage::
        with _Tee(path):
            run_models()   # all output goes to terminal AND file
    """
    def __init__(self, filepath: Path):
        self._filepath: Path              = filepath
        self._orig_out                    = sys.stdout
        self._fh: Optional[IOBase]        = None

    def write(self, data: str) -> None:
        self._orig_out.write(data)
        if self._fh:
            self._fh.write(data)

    def flush(self) -> None:
        self._orig_out.flush()
        if self._fh:
            self._fh.flush()

    def __enter__(self):
        self._fh = open(self._filepath, 'w', encoding='utf-8')
        sys.stdout = self
        return self

    def __exit__(self, *_):
        sys.stdout = self._orig_out
        self._fh.close()
        print(f"\n[OUTPUT] Results transcript saved \u2192 {self._filepath}")


# ====================================================================================
# PATH CONFIGURATION
# ====================================================================================
make_all_dirs()
OUT_FILE  = OUT_11_RESULTS   # plain-text transcript of all results


# ====================================================================================
# CONFIGURATION
# ====================================================================================
MASTER_FILE = INT_REGIONAL_AVG

# Under the k=5 partition all clusters are analytically usable — the original
# old-k=6 exclusions (C5 tidal, C6 lake-buffered) targeted small-n / unreliable
# groups that were cleaned out at the partition level. EXCLUDED_CLUSTERS is
# kept (rather than the logic deleted) for backward compatibility, but is
# expected to be empty under the current partition.
EXCLUDED_CLUSTERS: set[str] = set()

# String-keyed cluster labels for the 'C1'..'CN' column convention used by
# the regional-averages CSV. Update utils.config.CLUSTER_LABELS — not this
# adapter — to change labels.
CLUSTER_LABELS_STR: dict[str, str] = {
    f"C{cid}": label for cid, label in CLUSTER_LABELS.items()
}

# Macro-block columns expected in the regional-averages CSV. Under the k=5
# Option-A partition Script 03 writes one block alias per cluster (BLOCK_MAP):
#     C1 → Lake_Edge,  C2 → Eastern_Block,  C3 → Western_Block,
#     C4 → Forest,     C5 → Coastal_Forest.
# All five participate in Section 2 forecasting. Wells from clusters whose
# block column is missing at runtime are silently skipped (handled by the
# `if block in df.columns` filter).
BLOCK_COLUMNS = [
    "Lake_Edge",
    "Eastern_Block",
    "Western_Block",
    "Forest",
    "Coastal_Forest",
]

SUMMER_MONTHS  = [4, 5, 6, 7, 8, 9]     # Apr-Sep  (drought / recession season)
WINTER_MONTHS  = [10, 11, 12, 1, 2, 3]  # Oct-Mar  (recharge / flood season)
MIN_VALID_MONTHS = 3                    # minimum months per season to include a hydrological year


def _load_cluster_peak_months() -> dict[str, int]:
    """
    Load CLUSTER_PEAK_MONTH from INT_CLUSTER_PEAK_MONTHS (written by
    Script 03's export_cluster_peak_months). The file is the single source of
    truth: it is derived from the long-term monthly means of the cluster-
    centroid hydrograph, and is regenerated each time Script 03 runs.

    Failing loudly if the file is missing is intentional — silently falling
    back to stale defaults would mean using forecasting horizons keyed to
    the wrong partition.
    """
    if not INT_CLUSTER_PEAK_MONTHS.exists():
        raise FileNotFoundError(
            f"Cluster peak-months file not found:\n  {INT_CLUSTER_PEAK_MONTHS}\n"
            f"Run script 03 (state-space model) first — it produces this file "
            f"as part of its regional-averages exports."
        )
    df = pd.read_csv(INT_CLUSTER_PEAK_MONTHS)
    if not {"cluster_id", "peak_month"}.issubset(df.columns):
        raise RuntimeError(
            f"{INT_CLUSTER_PEAK_MONTHS.name} is missing expected columns "
            f"'cluster_id' and 'peak_month'. Re-run script 03 to regenerate."
        )
    return {f"C{int(row['cluster_id'])}": int(row["peak_month"])
            for _, row in df.iterrows()}


# Cluster-specific horizon: months from October (start of hydrological winter)
# to each cluster's historical mean peak month, inclusive. Loaded from
# INT_CLUSTER_PEAK_MONTHS (script 03 output) so the values stay in sync with
# the partition. See Section 3.6.3 of Hollingham (2026) for the methodology.
CLUSTER_PEAK_MONTH = _load_cluster_peak_months()


# ====================================================================================
# HELPERS
# ====================================================================================
def load_data(filepath: 'str | Path') -> pd.DataFrame:
    """Load 03_regional_averages.csv and validate its structure."""
    if not os.path.exists(filepath):
        sys.exit(
            f"\n[ERROR] Required input file not found: '{filepath}'\n"
            "        Please run 03_state_space_model.py first to generate this file.\n"
        )
    df = pd.read_csv(filepath, index_col='Date', parse_dates=True)
    required = {'P_mm', 'PET_mm', 'Western_Block', 'Eastern_Block'}
    missing = required - set(df.columns)
    if missing:
        sys.exit(
            f"\n[ERROR] '{filepath}' is missing expected columns: {missing}\n"
            "        Please re-run 03_state_space_model.py to regenerate the file.\n"
        )
    return df


def sep(title: str, width: int = 70) -> str:
    """Return a formatted section header string."""
    return f"\n{'=' * width}\n{title}\n{'=' * width}"


def _horizon_months(peak_month: int) -> list:
    """Return [10, 11, ..., peak_month] as a sequence of calendar months."""
    months, m = [], 10
    for _ in range(12):
        months.append(m)
        if m == peak_month:
            return months
        m = (m % 12) + 1
    return months


def _climatology_from_regional(df: pd.DataFrame) -> tuple:
    """Compute long-term monthly mean P and PET from the regional averages frame.
    Returns (P_clim, PET_clim) as dicts keyed by calendar month 1..12."""
    df = df.copy()
    df.index = pd.to_datetime(df.index)
    P_clim   = df.groupby(df.index.month)['P_mm'].mean().to_dict()
    PET_clim = df.groupby(df.index.month)['PET_mm'].mean().to_dict()
    return P_clim, PET_clim



# ====================================================================================
# SECTION 1: MECHANISTIC STATE-SPACE EQUATIONS (read from Script 03)
# ====================================================================================
def run_state_space(df: pd.DataFrame) -> dict:
    """
    Load cluster-level SSM coefficients from Script 03's mechanistic
    coefficients table (03_03_cluster_mechanistic_coefficients.csv).

    Script 03 fits the lag-1 SSM to each cluster centroid hydrograph:
        dh_t = b1*P_{t-1} - b2*PET_{t-1} - b3*h_{t-1}

    with rainfall and PET in metres (P_m, PET_m) and head in metres,
    so b1 and b2 are in m/m (dimensionless).  This function converts
    them to m/mm (/ 1000) for consistency with the downstream P_flood
    closed form (Section 3), which uses climatological P and PET in mm.

    Previously this function fitted its own lag-0 OLS on the cluster-
    average hydrographs from 03_regional_averages.csv. That independent
    fit produced weaker b1 values (lag-0 misses the 1-month recharge
    delay) and is superseded by the Script 03 lag-1 centroid fits.

    Returns:
        results_dict: {cluster_name: {beta1, beta2, beta3, r2, n}}
            b1, b2 in m/mm;  b3 dimensionless (positive).
    """
    print(sep("SECTION 1: MECHANISTIC STATE-SPACE EQUATIONS  (dh = b1*P - b2*PET - b3*h_prev)"))
    print("  Cluster-centroid lag-1 coefficients from Script 03")
    print(f"  Source: {OUT_03_MECHANISTIC_TABLE.name}\n")

    if not OUT_03_MECHANISTIC_TABLE.exists():
        sys.exit(
            f"\n[ERROR] Mechanistic coefficients file not found:\n"
            f"  {OUT_03_MECHANISTIC_TABLE}\n"
            f"  Run Script 03 (state-space model) first.\n"
        )

    cc = pd.read_csv(OUT_03_MECHANISTIC_TABLE)
    cluster_labels = CLUSTER_LABELS_STR
    results_dict = {}

    for _, row in cc.iterrows():
        cid = int(row["Cluster"])
        col = f"C{cid}"
        if col in EXCLUDED_CLUSTERS:
            continue

        # Script 03 stores beta in m/m (regression on P_m in metres).
        # Section 3 uses P_clim and PET_clim in mm, so convert to m/mm.
        b1 = float(row["beta_1"]) / 1000.0   # m/m -> m/mm
        b2 = float(row["beta_2"]) / 1000.0   # m/m -> m/mm
        b3_raw = float(row["beta_3"])
        if b3_raw < 0:
            print(f"  [WARNING] {col}: β₃ = {b3_raw:.4f} is negative "
                  f"(expected positive under displacement formulation). "
                  f"Using abs() but investigate upstream.")
        b3 = abs(b3_raw)                         # dimensionless, ensure positive

        r2 = float(row["R2"])
        n  = int(row["n"])

        pb1 = float(row["pvalue_beta_1"])
        pb2 = float(row["pvalue_beta_2"])
        pb3 = float(row["pvalue_beta_3"])

        label = cluster_labels.get(col, col)
        print(
            f"  {label}:  dh = ({b1:.6f}*P) - ({b2:.6f}*PET) - ({b3:.4f}*h_prev)"
            f"   |  R2 = {r2:.3f}   n = {n}"
        )
        print(
            f"        p-values:  P = {pb1:.4e}   PET = {pb2:.4e}   h_prev = {pb3:.4e}"
        )

        results_dict[col] = {
            'beta1': b1,
            'beta2': b2,
            'beta3': b3,
            'r2':    r2,
            'n':     n,
        }

    if EXCLUDED_CLUSTERS:
        print(f"\n  Excluded from mechanistic model: {', '.join(sorted(EXCLUDED_CLUSTERS))}")

    return results_dict



# ====================================================================================
# SECTION 2: PEAK FLOOD TRANSFER FUNCTIONS
# ====================================================================================
def run_peak_forecasting(df: pd.DataFrame) -> None:
    """
    Fit empirical peak-flood transfer functions for available blocks
    (Western, Eastern, and Forest where provided).

    For each Hydrological Year (Oct 1 - Sep 30):
        h_min    = minimum water level over Apr-Sep  (summer drought memory)
        P_winter = cumulative precipitation over Oct-Mar
        h_peak   = maximum water level over Oct-Mar  (target variable)

    Regression (OLS with intercept):
        h_peak = \u03b2\u2081\u00b7P_winter + \u03b2\u2082\u00b7h_min + c
    """
    print(sep("SECTION 2: PEAK FLOOD TRANSFER FUNCTIONS  (h_peak = \u03b2\u2081\u00b7P_winter + \u03b2\u2082\u00b7h_min + c)"))
    print("  OLS with intercept | Hydrological year: Oct 1 - Sep 30")
    print("  Blocks (one per cluster, k=5 partition): Lake_Edge (C1), "
          "Eastern_Block (C2), Western_Block (C3), Forest (C4), Coastal_Forest (C5).\n")

    df = df.copy()
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()

    df['Hydro_Year'] = df.index.year + (df.index.month >= 10).astype(int)

    blocks = [block for block in BLOCK_COLUMNS if block in df.columns]
    table6_rows = []
    for block in blocks:
        yearly_data = []

        for year, subset in df.groupby('Hydro_Year'):
            summer = subset[subset.index.month.isin(SUMMER_MONTHS)][[block]].dropna()
            winter = subset[subset.index.month.isin(WINTER_MONTHS)][[block, 'P_mm']].dropna()

            if len(summer) >= MIN_VALID_MONTHS and len(winter) >= MIN_VALID_MONTHS:
                yearly_data.append({
                    'h_peak':   winter[block].max(),
                    'h_min':    summer[block].min(),
                    'P_winter': winter['P_mm'].sum(),
                })

        hydro_df = pd.DataFrame(yearly_data).dropna()

        if len(hydro_df) < 5:
            print(f"  {block}: Insufficient hydrological years ({len(hydro_df)}) - skipped.")
            continue

        X     = sm.add_constant(hydro_df[['P_winter', 'h_min']])
        model = sm.OLS(hydro_df['h_peak'], X).fit()

        c   = model.params['const']
        b1  = model.params['P_winter']
        b2  = model.params['h_min']
        pc  = model.pvalues['const']
        pb1 = model.pvalues['P_winter']
        pb2 = model.pvalues['h_min']

        print(f"  {block}:")
        print(f"    h_peak = ({b1:.5f}\u00b7P_winter) + ({b2:.3f}\u00b7h_min) {'+' if c >= 0 else '-'} {abs(c):.3f}")
        print(f"    R\u00b2 = {model.rsquared:.3f}   |   n = {len(hydro_df)} hydrological years")
        print(f"    p-values:  P_winter = {pb1:.4f}   h_min = {pb2:.4f}   intercept = {pc:.4f}")
        print()

        table6_rows.append({
            'Block': block,
            'beta_1_P_winter': float(b1),
            'beta_2_h_min': float(b2),
            'intercept': float(c),
            'R2': float(model.rsquared),
            'n_hydrological_years': int(len(hydro_df)),
            'p_value_P_winter': float(pb1),
            'p_value_h_min': float(pb2),
            'p_value_intercept': float(pc),
            'equation': f"h_peak = ({b1:.5f}*P_winter) + ({b2:.3f}*h_min) {'+' if c >= 0 else '-'} {abs(c):.3f}",
        })

    pd.DataFrame(table6_rows).to_csv(OUT_11_TABLE6_WINTER, index=False)


# ====================================================================================
# SECTION 3: CRITICAL RAINFALL THRESHOLD EQUATIONS (iterated closed form)
# ====================================================================================
def run_critical_flood_thresholds(results_dict: dict, df: pd.DataFrame) -> None:
    """
    Derive P_flood for each cluster as the cumulative winter rainfall required
    to raise the water table from its summer minimum (h_0) to the slack-floor
    target (h_target = 0 m) over the cluster-specific horizon from October to
    the historical peak month.

    Derivation (see Section 3.6.3 of Hollingham 2026):

        Monthly recurrence (PET retained):
            h_t = \u03b1\u00b7h_{t-1} + \u03b2\u2081\u00b7P_t \u2212 \u03b2\u2082\u00b7E_t        (\u03b1 = 1 \u2212 \u03b2\u2083)

        With P_t = \u03bb\u00b7P_clim(t) and E_t = E_clim(t), iterating from h_0 over
        n monthly steps yields:
            h_n = h_0\u00b7\u03b1\u207f + \u03b2\u2081\u00b7\u03bb\u00b7S_P \u2212 \u03b2\u2082\u00b7S_E

        where S_P = \u03a3 \u03b1^(n-i)\u00b7P_clim(month_i),
              S_E = \u03a3 \u03b1^(n-i)\u00b7E_clim(month_i).

        Solving h_n = h_target for \u03bb:
            \u03bb = (h_target \u2212 h_0\u00b7\u03b1\u207f + \u03b2\u2082\u00b7S_E) / (\u03b2\u2081\u00b7S_P)

        Cumulative rainfall threshold:
            P_flood = \u03bb \u00b7 \u03a3 P_clim(month_i)

    The previous single-step formulation is retained in the output CSV under
    "P_flood_old_single_step_mm" for continuity with earlier report drafts.

    Parameters
    ----------
    results_dict : dict
        Output of run_state_space(); must contain b1, b2, b3 per cluster.
    df : pd.DataFrame
        Regional averages frame (for climatology and h_0 extraction).

    Assumptions
    -----------
    - h values are in metres below ground (negative below surface).
    - h_0 is the cluster long-term mean of the month-of-minimum head.
    - h_target = 0 m (surface flooding; slack-floor threshold).
    - Monthly rainfall scales uniformly by \u03bb; PET held at climatology.
    - \u03b2\u2083 stored positive after sign-inversion; applied as \u03b1 = 1 \u2212 \u03b2\u2083.
    """
    print(sep("SECTION 3: CRITICAL RAINFALL THRESHOLD EQUATIONS  (P_flood - iterated)"))
    print("  Iterated closed form from cluster-level SSM coefficients.")
    print("  Monthly rainfall scales by \u03bb; PET from RAF Valley climatology.\n")

    P_clim, PET_clim = _climatology_from_regional(df)

    cluster_labels = CLUSTER_LABELS_STR

    # Extract h_0 per cluster: long-term mean of the month with minimum head
    df_idx = df.copy()
    df_idx.index = pd.to_datetime(df_idx.index)
    h0_lookup = {}
    for cluster in cluster_labels:
        if cluster not in df_idx.columns:
            continue
        monthly = df_idx.groupby(df_idx.index.month)[cluster].mean()
        h0_lookup[cluster] = float(monthly.min())

    H_TARGET = 0.0   # slack floor = ground surface

    table8_rows = []
    for cluster in sorted(cluster_labels, key=lambda k: int(k[1:])):
        if cluster not in results_dict:
            print(f"  {cluster_labels[cluster]}: no fitted parameters - skipped.")
            continue
        if cluster not in h0_lookup:
            print(f"  {cluster_labels[cluster]}: no h_0 from regional averages - skipped.")
            continue

        b1 = results_dict[cluster]['beta1']
        b2 = results_dict[cluster]['beta2']
        b3 = results_dict[cluster]['beta3']
        h_0 = h0_lookup[cluster]
        peak_month = CLUSTER_PEAK_MONTH.get(cluster)
        if peak_month is None:
            print(f"  {cluster_labels[cluster]}: no peak month defined - skipped.")
            continue

        months = _horizon_months(peak_month)
        n = len(months)
        alpha = 1.0 - b3
        alpha_n = alpha ** n

        S_P = sum(alpha ** (n - 1 - i) * P_clim[m]   for i, m in enumerate(months))
        S_E = sum(alpha ** (n - 1 - i) * PET_clim[m] for i, m in enumerate(months))
        P_clim_total   = sum(P_clim[m] for m in months)
        PET_clim_total = sum(PET_clim[m] for m in months)

        lam        = (H_TARGET - h_0 * alpha_n + b2 * S_E) / (b1 * S_P)
        P_flood_new = lam * P_clim_total

        # ── Collapsed linear form:  P_flood = A*d + B  (d = positive depth below ground) ──
        # Derivation: with h_target = 0 and h_0 = -d (depth expressed as positive metres
        # below ground), the iterated closed form becomes
        #     P_flood = (d * alpha^n / (b1 * S_P) + b2 * S_E / (b1 * S_P)) * P_clim_total
        # i.e.
        #     A = (alpha^n * P_clim_total) / (b1 * S_P)
        #     B = (b2 * S_E * P_clim_total) / (b1 * S_P)
        # The collapsed form is algebraically exact, not an approximation.
        denom_b1_sp = b1 * S_P
        slope_A     = (alpha_n * P_clim_total) / denom_b1_sp
        intercept_B = (b2 * S_E * P_clim_total) / denom_b1_sp
        # Spreadsheet formula assumes d is entered in cell A2 as positive metres.
        spreadsheet_formula = f"=({slope_A:.2f}*A2+{intercept_B:.2f})"

        # Retained single-step value for continuity
        h_gap      = H_TARGET - h_0
        P_flood_old = (h_gap + b3 * h_0) / b1

        print(f"  {cluster_labels[cluster]}")
        print(f"    h_0 = {h_0:+.3f} m  (long-term mean of month-of-minimum)")
        print(f"    horizon: {months}  (n = {n} months, peak = month {peak_month})")
        print(f"    \u03b1 = {alpha:.4f}   \u03b1\u207f = {alpha_n:.4f}")
        print(f"    S_P = {S_P:7.1f} mm    S_E = {S_E:7.1f} mm")
        print(f"    climatological totals: P = {P_clim_total:.0f} mm   PET = {PET_clim_total:.0f} mm")
        print(f"    \u03bb = {lam:.3f}")
        print(f"    P_flood (iterated)    = {P_flood_new:5.0f} mm    [{lam:.2f}x climatology]")
        print(f"    P_flood (old 1-step)  = {P_flood_old:5.0f} mm    [reference only]")
        print(f"    Collapsed form:  P_flood = {slope_A:6.2f} * d + {intercept_B:6.2f}   "
              f"(d in m below ground)")
        print()

        latex_general = (
            r"P_{\mathrm{flood}} = \lambda \sum_{i=1}^{n} \bar P_i, \quad "
            r"\lambda = \frac{h_{\mathrm{target}} - h_0 \alpha^n + \beta_2 S_E}"
            r"{\beta_1 S_P}"
        )
        latex_numerical = (
            rf"P_{{\mathrm{{flood}}}}^{{{cluster}}} = "
            rf"\frac{{{H_TARGET:.2f} - ({h_0:+.3f})({alpha_n:.4f}) + "
            rf"({b2:.5f})({S_E:.2f})}}"
            rf"{{({b1:.5f})({S_P:.2f})}} \cdot {P_clim_total:.0f}"
        )
        latex_collapsed = (
            rf"P_{{\mathrm{{flood}}}}^{{{cluster}}} = "
            rf"{slope_A:.2f} \, d + {intercept_B:.2f}"
        )

        table8_rows.append({
            'Cluster':           cluster,
            'Label':             cluster_labels[cluster],
            'beta_1':            float(b1),
            'beta_2':            float(b2),
            'beta_3':            float(b3),
            'alpha':             float(alpha),
            'horizon_months':    n,
            'peak_month':        peak_month,
            'months_in_horizon': ','.join(str(m) for m in months),
            'h_0_m':             float(h_0),
            'h_target_m':        float(H_TARGET),
            'S_P_mm':            float(S_P),
            'S_E_mm':            float(S_E),
            'P_clim_total_mm':   float(P_clim_total),
            'PET_clim_total_mm': float(PET_clim_total),
            'lambda':            float(lam),
            'P_flood_new_mm':    float(P_flood_new),
            'P_flood_old_single_step_mm': float(P_flood_old),
            'slope_A':           float(slope_A),
            'intercept_B':       float(intercept_B),
            'spreadsheet_formula': spreadsheet_formula,
            'latex_general':     latex_general,
            'latex_numerical':   latex_numerical,
            'latex_collapsed':   latex_collapsed,
        })

    print("Note: P_flood_new supersedes the single-step formulation in prior drafts.")
    print("      See Section 3.6.3 of Hollingham (2026) for derivation.\n")

    pd.DataFrame(table8_rows).to_csv(OUT_11_TABLE8_THRESHOLDS, index=False)


# ====================================================================================
# SECTION 4: SUMMER DROUGHT TRANSFER FUNCTIONS
# ====================================================================================
def run_summer_drought_forecasting(df: pd.DataFrame) -> None:
    """
    Fit empirical summer drought transfer functions for available blocks
    (Western, Eastern, and Forest where provided).

    For each Hydrological Year (Oct 1 - Sep 30):
        h_max_winter = maximum water level over Oct-Mar (antecedent winter storage)
        P_summer     = cumulative precipitation over Apr-Sep
        h_min_summer = minimum water level over Apr-Sep (target drought variable)

    Regression (OLS with intercept):
        h_min_summer = \u03b2\u2081\u00b7P_summer + \u03b2\u2082\u00b7h_max_winter + c
    """
    print(sep("SECTION 4: SUMMER DROUGHT TRANSFER FUNCTIONS  "
              "(h_min = \u03b2\u2081\u00b7P_summer + \u03b2\u2082\u00b7h_max_winter + c)"))
    print("  OLS with intercept | Hydrological year: Oct 1 - Sep 30")
    print("  Predicting summer minimum from antecedent winter peak and summer rain.\n")

    df = df.copy()
    df.index = pd.to_datetime(df.index)
    df = df.sort_index()
    df['Hydro_Year'] = df.index.year + (df.index.month >= 10).astype(int)

    blocks = [block for block in BLOCK_COLUMNS if block in df.columns]
    table7_rows = []
    for block in blocks:
        yearly_data = []

        for year, subset in df.groupby('Hydro_Year'):
            winter = subset[subset.index.month.isin(WINTER_MONTHS)][[block]].dropna()
            summer = subset[subset.index.month.isin(SUMMER_MONTHS)][[block, 'P_mm']].dropna()

            if len(summer) >= MIN_VALID_MONTHS and len(winter) >= MIN_VALID_MONTHS:
                yearly_data.append({
                    'h_min_summer': summer[block].min(),
                    'h_max_winter': winter[block].max(),
                    'P_summer':     summer['P_mm'].sum(),
                })

        hydro_df = pd.DataFrame(yearly_data).dropna()

        if len(hydro_df) < 5:
            print(f"  {block}: Insufficient hydrological years ({len(hydro_df)}) - skipped.")
            continue

        X     = sm.add_constant(hydro_df[['P_summer', 'h_max_winter']])
        model = sm.OLS(hydro_df['h_min_summer'], X).fit()

        c   = model.params['const']
        b1  = model.params['P_summer']
        b2  = model.params['h_max_winter']
        pc  = model.pvalues['const']
        pb1 = model.pvalues['P_summer']
        pb2 = model.pvalues['h_max_winter']

        print(f"  {block}:")
        print(f"    h_min_summer = ({b1:.5f}\u00b7P_summer) + ({b2:.3f}\u00b7h_max_winter) "
              f"{'+' if c >= 0 else '-'} {abs(c):.3f}")
        print(f"    R\u00b2 = {model.rsquared:.3f}   |   n = {len(hydro_df)} hydrological years")
        print(f"    p-values:  P_summer = {pb1:.4f}   h_max_winter = {pb2:.4f}   intercept = {pc:.4f}")
        print()

        table7_rows.append({
            'Block': block,
            'beta_1_P_summer': float(b1),
            'beta_2_h_max_winter': float(b2),
            'intercept': float(c),
            'R2': float(model.rsquared),
            'n_hydrological_years': int(len(hydro_df)),
            'p_value_P_summer': float(pb1),
            'p_value_h_max_winter': float(pb2),
            'p_value_intercept': float(pc),
            'equation': f"h_min_summer = ({b1:.5f}*P_summer) + ({b2:.3f}*h_max_winter) "
                        f"{'+' if c >= 0 else '-'} {abs(c):.3f}",
        })

    pd.DataFrame(table7_rows).to_csv(OUT_11_TABLE7_SUMMER, index=False)


# ====================================================================================
# ENTRY POINT
# ====================================================================================
def run_models() -> None:
    print("\nLoading input data...")
    df = load_data(MASTER_FILE)
    print(f"  [OK] {len(df)} monthly rows loaded | "
          f"Columns: {', '.join(df.columns.tolist())}")

    results_dict = run_state_space(df)
    run_peak_forecasting(df)
    run_summer_drought_forecasting(df)
    run_critical_flood_thresholds(results_dict, df)

    print("\n" + "=" * 70)
    print("  Analysis complete.")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    make_all_dirs()
    with _Tee(OUT_FILE):
        run_models()
